### ISSUE TITLE
Programmatic deep linking (was: Retrieve existing link)

### ISSUE THREAD

**Issue by kevinresol** [BranchMetrics/react-native-branch-deep-linking-attribution#243]
Need an API that corresponds to this: https://github.com/BranchMetrics/branch-deep-linking-public-api#viewing-state-of-existing-deep-linking-urls

Given a existing branch link: `https://bnc.lt/m/7IhbRIjjmp`
The API should return the data:

```js
{
   "channel": "twitter",
   "campaign": "twitter-november-campaign",
   "feature": "share-button",
   "data": {
       "photo_id": "51",
       "valid": "true",
       "photo_name": "John Smith",
       "$og_image_url": "https://imgur.com/abcd",
       "~id": "123456789",
       "url": "https://bnc.lt/test-link"
   },
   "alias": "test-link",
   "type": 0
}
```

**Comment by jdee** [comment]
Hi @kevinresol. This functionality is not present in the underlying native SDKs for various reasons. It's not clear what the use case would be that would require it. Can you elaborate on how you want to use it?

**Comment by kevinresol** [comment]
I have an in-app QR code scanner that scans branch links. Then I need to get the parameters of the scanned link. Currently I have to use the REST api to do the job.

**Comment by jdee** [comment]
To be perfectly frank, I think this is something that Branch doesn't want to support. Branch doesn't want to build a data storage service based on deep links. I'm an external contractor, so I may have that slightly wrong. But I think the idea is that you should have that information anyway in your system, and you can probably look it up there just as easily (though I know it doesn't always work out to be that easy to add an endpoint to your API). I think the Branch REST API is intended more for use by servers, and you generally only retrieve the params for a link when the user opens it.

**Comment by jdee** [comment]
@kevinresol I realized after posting the previous comment that there is something you can do fairly easily in the native SDKs that may require an addition to this one. If you are only trying to open the link when the user scans it, then in the iOS SDK, e.g., you would call `Branch.getInstance().handleDeepLink(url)`. That would result in a callback to all subscribers to `branch.subscribe`. There are native mechanisms for triggering a link open that may need to be exposed to JS. If that's your use case, I'll look into what's necessary to expose that on both platforms.

This is different from just looking up the parameters. Support for that does not exist in the native SDKs for this SDK to wrap.

**Comment by kevinresol** [comment]
Thanks very much for the information. I suppose your `handleDeepLink(url)` is good enough for my use case. Because ultimately I just wanted to manually trigger the link inside the app (without going through the browser)

However, you said:

> But I think the idea is that you should have that information anyway in your system, and you can probably look it up there just as easily

Not sure why I want to duplicate and store the parameters separately. It causes a lot of problems including desync. IMHO, branch link is a solution of deep linking, which means it should facilitate _going to a deep page inside an app from virtually anywhere_, including from inside the same app. Even I use `subscribe()` I am going to act according to the params anyway, so I don't understand why getting the params manually is not a choice. But surely if I can manually trigger the event chain through `handleDeepLink(url)` it would be good too.

On the other hand, I don't see the how the REST api is intended for server use, given it uses the Branch (public) keys, which is also used on client apps anyway, instead of secret keys.

**Comment by jdee** [comment]
I apologize. I was confused by the use of `GET /url`, which is a red herring.

I'm adding a method called `branch.openURL`. This does not go through the operating system or the browser. It simply uses the SDK directly to do exactly what you want, but by correctly using a `POST /open` request and handling all the details. This functionality was just never exposed to the RN SDK before. This method will be appropriate for opening links from anywhere in the app, as you say: a push notification, a QR reader, a text input, whatever you like. This works perfectly on iOS. I'm still finishing up Android. I hope I'll have something in the master branch by the end of the day.

For clarity's sake, regarding my first reply: There is no support for the `GET /url` endpoint in the native SDKs. In fact, I believe it may previously have existed and was later deliberately removed. When I asked about it, I found resistance to any use of it in client apps. I didn't have a clear understanding of the matter until after my first reply. When I later realized you had no way to trigger a link open from JS, I finally understood both your problem and Branch's objections. They specifically want to discourage exactly what you were trying to do: Following deep links using the `GET /url` endpoint. The reasons: 1. Incorrect analytics. 2. Unexpected use cases. 3. Support difficulties. I think using that endpoint potentially introduces a lot of little problems that are normally handled by the native SDKs.

Not realizing yet that you didn't have the method you need, I wasn't sure why you would need to get access to a link _without opening it_, which is the only thing the `GET /url` endpoint is good for. I think this is not an unreasonable use case, but generally speaking, you probably took the parameters to create the link from a server anyway. If you have, say, a news app with a feed, and an article from that feed that includes a Branch link, there should be no reason you can't take the params from the feed instead. That was the thinking behind my first reply. But there can be other use cases where it might be useful. I think Branch mainly just wants to discourage using this endpoint to route links in your app.

All that said, I think it might be better if Branch used technical means to prevent undesirable use cases. Nothing other than advice prevents an app from doing something Branch would prefer the app not do.

Anyway, I apologize for muddying the waters. I'll have something for you quite soon.

**Comment by jdee** [comment]
In the master branch, there is now a `branch.openURL` method that can be used for this purpose. The iOS support is unlikely to change. There are some issues with webviews in Android, and in a pure RN app, the entire app runs in a webview (if I'm not mistaken). There are two options for Android:

1. Finish the current activity and start a new instance of the main activity when a link is opened. This is simplest and recommended by the Android team. But this results in a new activity window as though the app were relaunched in testing with a pure RN app. This UX may not be desirable.

```js
branch.openURL("https://myapp.app.link/xyz", {newActivity: true})
```

2. Move the call to `RNBranch.initSession` in MainActivity.java from `onStart` to `onResume`. This results in a better UX. It also results in a small delay in opening any link, since `onResume` is called later than `onStart`.

```js
branch.openURL("https://myapp.app.link/xyz") // only works if initSession moved to onResume
```

There is a new section for this in the README: https://github.com/BranchMetrics/react-native-branch-deep-linking#programmatic-deep-linking.

This will probably undergo further changes before release.

**Comment by jdee** [comment]
There is also now a `browser_example` app that demonstrates the use of this method.
