### ISSUE TITLE
Add setting for maximum number of event occurrence that triggers the reward

### ISSUE THREAD

**Issue by mieszko4** [BranchMetrics/react-native-branch-deep-linking-attribution#320]
It would be great to see  for maximum number of event occurrence that triggers the reward setting in branch dashboard.

**Comment by jdee** [comment]
@mieszko4 Can you be more specific about what you want to see? Is this a feature in the native SDKs that hasn't been exposed? Or is this a general enhancement you'd like to have? In either case, it has to be done in the native SDKs first, but it probably isn't much work to expose it to RN.

**Comment by mieszko4** [comment]
Sorry, I should have been given some example.

I think that I needed the following scenario on Referrals Reward rules on Branch Dashboard:
Currently I can set reward each time some event occurs or every time some event occurs.
But I am not able to set reward only for first 10 times for example.
This was a feature request.

**Comment by gdeluna-branch** [comment]
Closing out old issues. Referral/reward features are deprecated.
