### ISSUE TITLE
AppContainer mounted multiple times after clicking on a branch URL

### ISSUE THREAD

**Issue by agmcleod** [BranchMetrics/react-native-branch-deep-linking-attribution#378]
Hi there,

I'm using this package to listen for branch deep links to navigate to different parts of the app. I noticed that this is causing multiple mounts of the component in the AppRegistry, which is a big problem with state.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/113275/46104005-3b61e680-c1a0-11e8-8d76-6b8f13b4ffa4.png">

When I do a `react-native run-android` and open the app, it's fine. Has a single container, and state management is okay. When i open gmail in the emulator, and click on the branch link. It opens the app, the subscribe gets called, but a second AppContainer appears. In this app i am dealing with hydration of the user's access token. I need to keep track when it changes, but this is not possible when the state is different for each instance opened.

**Comment by sequoiaat** [comment]
@agmcleod could you please share us the dev environment details

**Comment by agmcleod** [comment]
@csalmi-branch i was able to work around it for the issue it caused, but the multiple mounts is still present.

**Comment by JofBigHealth** [comment]
I'm not 100% confident with this analysis as I'm not an Android expert. But here goes:

Our problem is that we had two ways of launching MainActivity; one via the splash screen and one via the icon. When clicking on a link or notification our app launched the SplashScreen activity which created a new intent which, I think, creates a new instance of ReactRouteView. I've seen the following pattern used in a lot of places so I suspect the problem isn't super rare:

```
// SplashActivity.java
public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
        finish();
    }
}
```
// MainActivity.java
public class MainActivity extends ReactActivity {
     @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ReactRootView mReactRootView = new ReactRootView(this);
    }
   ...etc
}

```
// AndroidManifest.xml
        <activity
            android:name="com.foo.SplashActivity"
            android:theme="@style/SplashTheme"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.foo.MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:exported="true"
            android:windowSoftInputMode="adjustNothing">
            <intent-filter android:label="filter_react_native">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="yourscheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

Not sure if that's relevant to your problems but maybe someone else will find this via google and it'll help them

**Comment by rickycpadilla** [comment]
My solution was to add `android:launchMode="singleTask"` to my `AndroidMainfest.xml` like:
```
<activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        ...
>
```
