### ISSUE TITLE
How do i retrieve the referee userid

### ISSUE THREAD

**Issue by Kiran0791** [BranchMetrics/react-native-branch-deep-linking-attribution#398]
How do i retrieve the userid at the time of installation using referral link. which was set using the below method
branch.setIdentity('12345')

**Comment by sequoiaat** [comment]
@Kiran0791  This feature is currently  not implemented  in react.  But  yes in the native sdk there is implementation for getIdentity https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/PrefHelper.java#L418 .

**Comment by jdee** [comment]
I'm sure we can address this in 3.0.0, maybe even a 2.x patch. This needs to go by Branch product management first. (I'm preparing a list of requested enhancements with estimates for them to make their decision.) But it's certainly not much work.
