### ISSUE TITLE
Trouble reaching the Branch servers, please try again shortly.

### ISSUE THREAD

**Issue by jamesholcomb** [BranchMetrics/react-native-branch-deep-linking-attribution#402]
Version 2.3.3
    RN 0.57.5
    Device iOS 11.4
    Android 8.1.0

This message shows up intermittently in my production app, always during an app load that is instigated by a push notification action.

`branch.subscribe` is called in the Application `componentDidMount`.  What is the recommended strategy for dealing with this error?  In the `subscribe` callback, the app performs additional setup that requires the `params` and app state.

**Comment by jamesholcomb** [comment]
Thanks @sequoiaat Yes, the device has a solid connection.

I did see that post (about the SDK trying again later). Does the RN module accommodate that?  I assumed that the `params` (which I need during setup) would not be available if an error existed in the subscribe callback.

**Comment by sequoiaat** [comment]
RN directly refers that from native sdk -
In the init session call, the error is handled in react sdk with the native reference. https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/android/src/main/java/io/branch/rnbranch/RNBranchModule.java#L102

**Comment by sequoiaat** [comment]
@jamesholcomb Yes if an error existed then params would not be available. RN module does accommodate that  - https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/android/src/main/java/io/branch/rnbranch/RNBranchModule.java#L102

aisles please refer to this link in example where it is handled - https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/examples/webview_example/src/ArticleList.js#L37

**Comment by jamesholcomb** [comment]
Sounds good.

**Comment by StarryFire** [comment]
@jamesholcomb  did you solve this problem?

**Comment by jamesholcomb** [comment]
@StarryFire https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/530#issuecomment-604699757
