### ISSUE TITLE
Bundle size is huge

### ISSUE THREAD

**Issue by danilobuerger** [BranchMetrics/react-native-branch-deep-linking-attribution#423]
Currently the bundle size is huge as everything is included. Should add and use a .npmignore that excludes at least docs and included assets.

**Comment by jdee** [comment]
We can't use .npmignore. This has been discussed before, though I'd have to dig out the previous conversation. We use a whitelist in package.json. This does not include everything. If you install the package from NPM, the bundle size is reasonable. How are you getting the SDK?

**Comment by danilobuerger** [comment]
@jdee Thanks for the quick response. Our react-native project has 1173 dependencies, with branch being third place with 7,4 MB (as a .tgz, 9 MB unpacked). Thats not what I would call reasonable. The assets folder (included in docs) makes up for ~75 % of that. Thats totally unnecessary. 
```
❯ curl -I https://registry.npmjs.org/react-native-branch/-/react-native-branch-2.3.4.tgz
content-length: 7408018
```
If its a whitelist, would it be possible to remove `docs`, or at least move `assets` out of doc? There is no need to bundle 7 MB of screenshots.

**Comment by jdee** [comment]
That's fair enough. In fact, the docs in that folder are mostly ancillary. The README itself is not included. If the README is not included, there's no point in including the docs folder.

**Comment by jdee** [comment]
Release 2.3.5 is out without the docs folder.

**Comment by csalmi-branch** [comment]
@danilobuerger Have you had a chance to review the new version (2.3.5) without the docs folder?

**Comment by danilobuerger** [comment]
@csalmi-branch Its now 860.867 bytes (tgz) compared to the 7.408.018 bytes (tgz) of 2.3.4. So a very nice decrease. However, I noticed another quiet large directory: `android/build`, this appears to be a leftover from CI testing (?) and should also be excluded.
