### ISSUE TITLE
duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by SavageWilliam** [BranchMetrics/react-native-branch-deep-linking-attribution#452]
We are just following the https://github.com/BranchMetrics/react-native-branch-deep-linking README (and also spent a ton of time reading through https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/convert-to-react-pod.md , numerous issues/comments in this repo), but we're still having iOS issues:

Specifically, when building the app on XCode (Version 10.1 (10B61)), we get:

```
...
Products/Debug-iphoneos/Branch/libBranch.a(BNCURLBlackList.o)
    /Users/savage/Library/Developer/Xcode/DerivedData/mobile-aqpuagjtqxdeygfqksvxebojqcnx/Build/Products/Debug-iphoneos/libreact-native-branch.a(BNCURLBlackList.o)
duplicate symbol _OBJC_CLASS_$_BNCKeyChain in:
    /Users/savage/Library/Developer/Xcode/DerivedData/mobile-aqpuagjtqxdeygfqksvxebojqcnx/Build/Products/Debug-iphoneos/Branch/libBranch.a(BNCKeyChain.o)
    /Users/savage/Library/Developer/Xcode/DerivedData/mobile-aqpuagjtqxdeygfqksvxebojqcnx/Build/Products/Debug-iphoneos/libreact-native-branch.a(BNCKeyChain.o)
duplicate symbol _OBJC_METACLASS_$_BNCKeyChain in:
    /Users/savage/Library/Developer/Xcode/DerivedData/mobile-aqpuagjtqxdeygfqksvxebojqcnx/Build/Products/Debug-iphoneos/Branch/libBranch.a(BNCKeyChain.o)
    /Users/savage/Library/Developer/Xcode/DerivedData/mobile-aqpuagjtqxdeygfqksvxebojqcnx/Build/Products/Debug-iphoneos/libreact-native-branch.a(BNCKeyChain.o)
duplicate symbol _SecCopyErrorMessageString in:
    /Users/savage/Library/Developer/Xcode/DerivedData/mobile-aqpuagjtqxdeygfqksvxebojqcnx/Build/Products/Debug-iphoneos/Branch/libBranch.a(BNCKeyChain.o)
    /Users/savage/Library/Developer/Xcode/DerivedData/mobile-aqpuagjtqxdeygfqksvxebojqcnx/Build/Products/Debug-iphoneos/libreact-native-branch.a(BNCKeyChain.o)
ld: 729 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

react-native info:
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 25.47 MB / 16.00 GB
      Shell: 5.6 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.0 - /var/folders/2t/gf_9q1052vlfv98z6ldlxxp00000gn/T/yarn--1557921163734-0.6208257388987857/node
      Yarn: 1.13.0 - /var/folders/2t/gf_9q1052vlfv98z6ldlxxp00000gn/T/yarn--1557921163734-0.6208257388987857/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
```

Our Podfile:

```
# Uncomment the next line to define a global platform for your project

target 'mobile' do
  platform :ios, '9.0'

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Stripe', '~> 14.0.0'
  # If you were to upgrade Intercom and/or react-native-intercom, make sure it does not crash on Release mode on iOS!
  pod 'Intercom', '=5.0.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging'

  # Pods for mobile
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'

  pod 'react-native-branch', :path => '../node_modules/react-native-branch'

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

File structure:
![image](https://user-images.githubusercontent.com/15717822/57773690-840ae780-7710-11e9-811e-a348851c7b05.png)

Any help is very much appreciated!

**Comment by jdee** [comment]
You have to remove the Libraries group. It conflicts with the Podfile. I think that's mentioned in the conversion instructions. Those static libraries conflict with the pods in the Podfile.

If you can revert to before you started the change (or run `pod deintegrate` to remove CocoaPods from your project), I have a conversion tool for you:

```bash
brew install jdee/tap/react_native_util
cd /path/to/app
rn react_pod
```

This requires macOS and Xcode. If you install from Homebrew, it additionally only requires the react-native-cli, which you obviously have. There is no other manual step. See https://github.com/jdee/react_native_util for more info and other installation options.

However, the react_pod command will fail if the project already uses CocoaPods. It's intended for a clean conversion, not to doctor and fix a project. Maybe a future release can do that. The tool is about a week old.

I won't be surprised if there are issues, but it works well on a fresh app created with `react-native init`. If you run into problems with react_native_util, please report them in that repo. Thanks.

**Comment by cihati** [comment]
@jdee We tried these, but it didn't work. But then someone else in our team pulled the branch (pun not intended =) from GitHub as it was, and it built without any issues (i.e. without applying your suggestions) and ran smoothly. Go figure!

**Comment by javi10823** [comment]
Hi @jdee  I have the same issue.

**Comment by KDederichs** [comment]
Similar issue here, updated from 0.59.10 to 0.60.0 to get rid of all the errors first before upgrading more and now I'm stuck with a bunch of duplicate symbol  errors.
I unlinked the library before using pods and my `Library` folder in Xcode is completely empty.
There's only the `libPods-MyProject.a` in the `Link Binary with Libraries` category.
They are all like 
```
/...../Build/Products/Debug-iphoneos/Branch/libBranch.a(BNCKeyChain.o)
/....../Build/Products/Debug-iphoneos/libreact-native-branch.a(BNCKeyChain.o)
```
though and I have not added any Branch related stuff to my Pod file. It just adds the `Development Pods/react-native-branch` and `Pods/Branch` folders by itself.
Anyone ever found a solution to that?

**Comment by echo-branch** [comment]
@KDederichs 0.60.0 does some linking magic.  This renders the pre-0.60.0 setup instructions invalid.  Basically, the old instructions have you do all the setup and linking yourself, RN now does it for you.  RN provides an upgrade guide, but I personally found it easier to regenerate my project and just copy over files.

https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked
