### ISSUE TITLE
CocoaPods 1.7.0 breaks iOS builds

### ISSUE THREAD

**Issue by jdee** [BranchMetrics/react-native-branch-deep-linking-attribution#461]
Reported in the CocoaPods repo: ~~https://github.com/CocoaPods/CocoaPods/issues/8857~~ https://github.com/CocoaPods/CocoaPods/issues/8836

See https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/450#issuecomment-495014208.

CocoaPods 1.7.0 changes where it generates certain code under the Pods directory. This means that `#import <react-native-branch/RNBranch.h>` will no longer compile. ~~Instead it has to be `#import <react_native_branch/RNBranch.h>`.~~ This is expected to be fixed in 1.7.1. You can temporarily change your import in order to build using 1.7.0, but it's probably best to stick with 1.6 until 1.7.1 is released. See also https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/461#issuecomment-496703048.

This can affect modules other than this one. There are a number of ways to pin your project to 1.6. The best is to use a Gemfile in the root of your project:

```Ruby
source 'https://rubygems.org'

gem 'cocoapods', '~> 1.6.0'
```

Then at the command line:

```bash
bundle install
bundle exec pod install
bundle exec pod update
# etc
```

This will ensure that your project always uses CP 1.6 until you're ready to update. It also allows you to use different versions of CocoaPods for different apps as well.

In addition, as an alternative to using a Gemfile, you can specify which version of an installed gem to use if more than one version is available:

```bash
[sudo] gem install cocoapods -v 1.6.1
gem list cocoapods
pod _1.6.1_ --version
pod _1.6.1_ install --repo-update
```

~~See #459 for a clean but dubious solution to the problem.~~

**Comment by jdee** [comment]
Another point here: It is common practice to check in the entire Pods folder generated by `pod install`. This is what is done in every example here. (The generated Carthage folder is also checked in with webview_example_carthage.) With CocoaPods, you should always commit the Podfile.lock and generated xcworkspace. Checking in the Pods folder can be a matter of debate, but it has some benefits.

1. You don't even have to have CocoaPods installed in order to build if all its products are committed to SCM. CocoaPods becomes a maintenance tool, not a development tool. And this completely insulates you against issues with different versions of CocoaPods. This issue will only arise when you run `pod install` or `pod update` with 1.7 instead of 1.6, which you can do at your leisure, once it's convenient for you.
2. It's possible for pods to be unpublished from CocoaPods, so `pod install` can succeed one day and fail the next. This argument always ended the debate for me with production apps.

The big downside is that including the Pods folder makes for a lot of noise in pull requests. One decent solution there (which I haven't really been following in this repo) is always to make `pod install` or `pod update` its own separate commit. This makes it easier to see what changes were made by hand and ignore the automated changes.

**Comment by jdee** [comment]
Note https://github.com/CocoaPods/CocoaPods/issues/8836. This is expected to be fixed in CocoaPods 1.7.1. For now, please use one of these solutions:

- Pin your app to CocoaPods 1.6.x as discussed above.
- Add `use_frameworks!` to your Podfile. Run `pod install` after modifying the Podfile. Change your import to `@import react_native_branch;` instead of `#import <react-native-branch/RNBranch.h>`.
- Change your import to `#import <react_native_branch/RNBranch.h>`, but be prepared to change it back when you update to CocoaPods 1.7.1.

**Comment by dnkoutso** [comment]
CocoaPods 1.7.1 shipped with the fix.

**Comment by jdee** [comment]
Thanks for the update @dnkoutso. This is reflected in #462, about to be merged. The docs.branch.io site will also be updated.
