### ISSUE TITLE
Race condition in `branch.getLatestReferringParams()` on Android

### ISSUE THREAD

**Issue by RoboTeddy** [BranchMetrics/react-native-branch-deep-linking-attribution#465]
`branch.getLatestReferringParams()` returns a `Promise`, which makes it seem that it will wait for initialization if necessary prior to resolving the promise. Indeed, it's documented this way:

> The getLatestReferringParams method is essentially a synchronous method that retrieves the latest referring link parameters stored by the native SDK. However, React Native does not support synchronous calls to native code from JavaScript, so the method returns a promise. You must await the response or use then to receive the result. The same remarks apply to the getFirstReferringParams method. However, this is only a restriction of React Native. The purpose of getLatestReferringParams is to retrieve those parameters one time. The promise will only return one result. It will not continue to return results when links are opened or wait for a link to be opened. This method is not intended to notify the app when a link has been opened.

But actually, the promise is a fake one that resolves immediately, rather than first waiting for Branch to finish initialization:

https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/8576c41b4887462e51b715794fd68b6dc91fe340/android/src/main/java/io/branch/rnbranch/RNBranchModule.java#L352

https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/4e36ede86fc329d9b6c94918f0b8d58eb76fc344/Branch-SDK/src/io/branch/referral/Branch.java#L2123

The release variant of my app fails to get the proper latest params for this reason. It was working on the debug variant. Haven't checked to see if it's the same case on iOS.

**Comment by RoboTeddy** [comment]
Here's a log demostrating the race condition -- I'm calling getLatestReferringParams() every 30 milliseconds, and you can see that the answer changes after Branch initialization completes:

```
06-25 11:10:38.452 2073-2113/? I/ReactNativeJS: 'latestReferringParams', {}
06-25 11:10:38.520 2073-2113/? I/ReactNativeJS: 'latestReferringParams', {}
06-25 11:10:38.590 2073-2113/? I/ReactNativeJS: 'latestReferringParams', {}
06-25 11:10:38.657 2073-2113/? I/ReactNativeJS: 'latestReferringParams', {}
06-25 11:10:38.723 2073-2113/? I/ReactNativeJS: 'latestReferringParams', {}
06-25 11:10:38.729 2073-2112/? I/BranchSDK: returned {"session_id":"REDACTED","identity_id":"REDACTED","link":"REDACTED","data":"{\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"REDACTED"}
06-25 11:10:38.740 2073-2073/? D/RNBranch: onInitFinished
06-25 11:10:38.751 2073-2134/? I/BranchSDK: getting https://api2.branch.io/v1/app-link-settings/REDACTED?metadata={}&sdk=android3.2.0&branch_key=REDACTED
06-25 11:10:38.756 2073-2073/? D/RNBranch: sendRNEvent
06-25 11:10:38.771 2073-2073/? D/RNBranch: Catalyst instance poller try 1
06-25 11:10:38.771 2073-2073/? D/RNBranch: Catalyst instance active
06-25 11:10:38.792 2073-2113/? I/ReactNativeJS: 'latestReferringParams', { '+is_first_session': false, '+clicked_branch_link': false }
06-25 11:10:38.831 2073-2134/? I/BranchSDK: returned {"android_uri_scheme":"REDACTED","ios_uri_scheme":"REDACTED","short_url_domain":"","default_short_url_domain":"REDACTED","alternate_short_url_domain":"REDACTED","android_package_name":"REDACTED","ios_bundle_id":"REDACTED","ios_team_id":"REDACTED"}
06-25 11:10:38.858 2073-2113/? I/ReactNativeJS: 'latestReferringParams', { '+is_first_session': false, '+clicked_branch_link': false }
06-25 11:10:38.925 2073-2113/? I/ReactNativeJS: 'latestReferringParams', { '+is_first_session': false, '+clicked_branch_link': false }
06-25 11:10:38.995 2073-2113/? I/ReactNativeJS: 'latestReferringParams', { '+is_first_session': false, '+clicked_branch_link': false }
```

**Comment by RoboTeddy** [comment]
Here's a workaround that returns a promise that won't resolve to params until branch has initialized:

```javascript
function getBranchLatestReferringParams() {
  return new Promise((resolve, reject) => {
    const unsubscribe = branch.subscribe(({error, params}) => {
      unsubscribe()
      if (error) reject(error)
      else resolve(params)
    })
  })
}
```

**Comment by msiddiq-branch** [comment]
@RoboTeddy could you please tell me which version of RN you are currently using? Also, can you confirm if you tried calling getLatestReferringParams() after waiting for subscribe method being called as getLatestReferringParams() returns value from the cache. 

Basically, when you try to read deeplink data immediately when the link is clicked you need to read the data under subscribe method and once data is available you can call getLatestReferringParams() for subsequent reads.

**Comment by RoboTeddy** [comment]
@msiddiq-branch RN 0.59. The workaround I pasted uses `subscribe` to do as you describe.

`getLatestReferringParams()` already returns a promise; you guys should make it wait to actually learn the referring params before it returns on the native side, if necessary! (If not, would document its behavior super super clearly, but even if you do that, you're probably gonna confuse a bunch of folks!)
