### ISSUE TITLE
[React Native] Using Branch with multiple Product Flavors on Android / Schemes on iOS

### ISSUE THREAD

**Issue by MateuszPrasal** [BranchMetrics/react-native-branch-deep-linking-attribution#476]
Hello!
I have one question about integration Branch with React Native. Is it possible to use Branch with multiple Product Flavors on Android / Schemes on iOS ? I tried looking for any informations about this issue but currently without success. Maybe exists any `branch.json` configuration which is compatible to multpile schemes? 

Thanks for all answers! :)

**Comment by jdee** [comment]
Please have a look at the examples.

- webview_example (and others) use separate debug configurations
- webview_example_native_ios uses different schemes to control keys

Please also this relevant document: https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/docs/branch-environments.md

**Comment by MateuszPrasal** [comment]
@jdee you are right, I didn't check much well. Thank you ! :)
