### ISSUE TITLE
Apple debug search ad showing up in release build??

### ISSUE THREAD

**Issue by m-pol** [BranchMetrics/react-native-branch-deep-linking-attribution#478]
I downloaded my first release build from TestFlight after integrating this repo and I'm getting this as the very first received link in branch.subscribe:

```
{
  "~branch_ad_format": "App Only",
  "~tags": [
    "LineName"
  ],
  "~ad_set_name": "AdGroupName",
  "~ad_set_id": "1234567890",
  "~advertising_partner_name": "Apple Search Ads",
  "~referring_link": "https://[my custom branch link domain]/a/[my branch live key]?%243p=a_apple&%7Ekeyword=Keyword&%7Etags=%5BLineName%5D&%7Eadvertising_partner_name=Apple+Search+Ads&%7Ebranch_ad_format=App+Only&%7Ecampaign=CampaignName&%7Ead_set_id=1234567890&%7Echannel=Apple+App+Store&%7Efeature=paid+advertising&%7Ead_set_name=AdGroupName&%7Ecampaign_id=1234567890",
  "~keyword": "Keyword",
  "~channel": "Apple App Store",
  "~campaign_id": "1234567890",
  "+click_timestamp": 1564004409,
  "+match_guaranteed": true,
  "+clicked_branch_link": true,
  "~feature": "paid advertising",
  "+is_first_session": false,
  "$3p": "a_apple",
  "~campaign": "CampaignName",
  "+rn_cached_initial_event": true
}
```

branch.ios.json:
```
{
  "branchKey": "[my branch live key]",
  "delayInitToCheckForSearchAds": true
}
```

I don't understand what I'm seeing here. Is this related to appleSearchAdsDebugMode? How could this possibly happen?

**Comment by m-pol** [comment]
It also happens in Debug builds if I set "delayInitToCheckForSearchAds" to true in branch.ios.debug.json:

```
{
  "debugMode": true,
  "branchKey": [my branch test key],
  "appleSearchAdsDebugMode": false,
  "delayInitToCheckForSearchAds": true
}
```

Why is delayInitToCheckForSearchAds causing it to find this bogus Search Ad, if appleSearchAdsDebugMode is false?

**Comment by jb4e** [comment]
We are seeing the same thing. This seems like a fairly serious bug.

**Comment by echo-branch** [comment]
This is default behavior for Apple Search Ads unless you're coming from the App Store.  If you wish to ignore this payload use the ignore option added in this release.

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/Branch-SDK/Branch.h#L641-L646

**Comment by lukebars** [comment]
Is it possible to ignore it in 4.3.0 while calling `getLatestReferringParams` ?

**Comment by echo-branch** [comment]
@lukebars 

Yes that's possible.  Within the iOS native AppDelegate, where you would init RNBranch, add the following.  

`

  [RNBranch.branch delayInitToCheckForSearchAds];
  [RNBranch.branch ignoreAppleSearchAdsTestData];
  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES]; // <-- add this
`

In the future I'd like to move a lot of the early lifecycle to the config file so you dont need to be in native code, but that's a ways off.
