### ISSUE TITLE
developer_identity does not reset after branch.logout()

### ISSUE THREAD

**Issue by maryasdk** [BranchMetrics/react-native-branch-deep-linking-attribution#484]
Hi there,

I am using react-native-branch 3.0.1
* I use a branch.setIdentity(userId) when a user signs in
* I use a branch.logout() when a user signs out

I was lately testing, and I noticed that after logging out, the developer_identity in the Branch dashboard Liveview does not reset. and still gives the userId of the user that signed out.

I am assuming this is a bug from branch side. Or is the documentation not clear and I should also setIdentity to null after logout?

**Comment by jdee** [comment]
The `logout` method is just exported from the native modules and calls directly into both SDKs. If you're experiencing an issue, it's likely that it's a native SDK issue. Can you reproduce the issue using the TestBed app from the relevant native repo?

**Comment by csalmi-branch** [comment]
@maryasdk were you able to reproduce this issue using the TestBed app as @jdee suggested? Do you see the issue on both iOS and Android, or on only one particular platform? 

I am wondering if this is actually a dashboard issue, versus a SDK issue, and will check with the dashboard team in case they have insight into this issue.
