### ISSUE TITLE
Cannot find interface declaration for 'BranchUniversalObject'

### ISSUE THREAD

**Issue by lalitkumar50678** [BranchMetrics/react-native-branch-deep-linking-attribution#485]
Hey in getting this issue after install react-native-branch 4.1.0 ,  react-native-branch 3.1.1 and react-native 4.0.0

**Note: ** i'm manual link the RNBranch.xcodeproj not use cocopods 

step 1) npm i react-native-branch
step 2) react-native link react-native-branch
step 3) #import <Branch/Branch.h> file not found
step 4) i change  #import "RNBranch.h" instead of #import <Branch/Branch.h>
step 5) now i'm getting this issue 
           ..node_modules/react-native-branch/ios/BranchUniversalObject+RNBranch.h:17:12:       Cannot find interface declaration for 'BranchUniversalObject'

react-native version = 0.60.0
react version = 16.8.6

**Comment by jdee** [comment]
We can't really support manual SDK integration. There are examples in the repo of integration using CocoaPods and Carthage.
