### ISSUE TITLE
AndroidX support for RN < 0.60 (Was: Version 3.1.2)

### ISSUE THREAD

**Issue by PeterKruzlics** [BranchMetrics/react-native-branch-deep-linking-attribution#488]
Hello, I noticed that there was a v3.1.2 created (https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/commit/089f982d84475701b916ea18281d3b56332065f1), though I'm not able to install it via npm: 

<img width="595" alt="Screen Shot 2019-08-14 at 4 27 54 PM" src="https://user-images.githubusercontent.com/6665648/63053745-7ea86f00-beb0-11e9-9253-5a83f8a0e300.png">

Would it be possible to get that release cut and published to npm? I'm mainly looking for androidx support while on RN 0.59. Thanks!

**Comment by jdee** [comment]
Version bumps are performed immediately after every release. There is no 3.1.2 except in the repo. It may never be released. You can always look at https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases to see what was released (as well as NPM).

I had no idea it was possible to use AndroidX with RN 0.59. I'll have to review and see what's necessary. You can always try 4.x and ignore the peer dependency warnings. Codewise 4.x is mainly a matter of AndroidX support.
