### ISSUE TITLE
No enum constant io.branch.referral.util.e.NTD

### ISSUE THREAD

**Issue by urtheone** [BranchMetrics/react-native-branch-deep-linking-attribution#489]
In my project, we use react native and android,when i Integrate branch into my project。Sometime this  will happen：
`   
     java.lang.IllegalArgumentException 
`

`
     No enum constant io.branch.referral.util.e.NTD
     com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
`

> 

1 java.lang.Enum.valueOf(Enum.java:258)
--
2 io.branch.referral.util.e.valueOf(CurrencyType.java:9)
3 io.branch.rnbranch.RNBranchModule.createContentMetadata(RNBranchModule.java:703)
4 io.branch.rnbranch.RNBranchModule.createBranchUniversalObject(RNBranchModule.java:869)
5 io.branch.rnbranch.RNBranchModule.createUniversalObject(RNBranchModule.java:333)
6 java.lang.reflect.Method.invoke(Native Method)
7 com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
8 com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
9 com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10 android.os.Handler.handleCallback(Handler.java:873)
11 android.os.Handler.dispatchMessage(Handler.java:99)
12 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
13 android.os.Looper.loop(Looper.java:214)
14 com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
15 java.lang.Thread.run(Thread.java:764)

> 

What can I do to reduce this？

**Comment by lixiaoma4639** [comment]
Because the Taiwan currency in enum CurrencyType uses TWD, and you pass NTD when you count, when you use the enumeration to enum.valueof(NTD), a crash occurs. It is better to modify the Taiwanese currency you pass as TWD.
