### ISSUE TITLE
[!] No podspec found for `Branch-SDK` in `../node_modules/react-native-branch/ios`

### ISSUE THREAD

**Issue by ebellumat** [BranchMetrics/react-native-branch-deep-linking-attribution#491]
After running ```yarn add react-native-branch``` to add the lib, i added on a podfile, but for the "Branch-sdk" the pod file doesn't exist.

```pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'```

![image](https://user-images.githubusercontent.com/26942680/63538069-850c9b80-c4ed-11e9-8f3e-308fe3464648.png)

```Fetching podspec for `Branch-SDK` from `../node_modules/react-native-branch/ios`
[!] No podspec found for `Branch-SDK` in `../node_modules/react-native-branch/ios```

How can i proceed if the Podspec doesn't exist? The version is "react-native-branch": "^3.1.1",

**Comment by saikiranoptisol** [comment]
@ebellumat  is there any solution that you got

**Comment by ebellumat** [comment]
Yes, i use the release from a tag from this repo. The NPM version is old...

just replace your react-native-branch in your package.json for this:

 "react-native-branch": "BranchMetrics/react-native-branch-deep-linking-attribution#v4.1.0"

**Comment by shchu** [comment]
Use Branch iOS SDK directly is work for me.

```
pod 'react-native-branch', path: '../node_modules/react-native-branch'
pod 'Branch', '0.27.1
```
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/docs/cocoapods.md#installation-without-the-react-pod

**Comment by aliberski** [comment]
Use only this one:
`pod 'react-native-branch', path: '../node_modules/react-native-branch'`

It includes Branch pod in its .podspec file ('Branch', '0.27.1')
