### ISSUE TITLE
Using UIWebView casue deprecation warning when uploading iOS build

### ISSUE THREAD

**Issue by radko93** [BranchMetrics/react-native-branch-deep-linking-attribution#492]
When uploading a build today I got an email from Apple regarding the deprecation of `UIWebView`.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs.

I found that the only library that still use `UIWebView` is `react-native-branch-deep-linking-attribution`. It has to be refactored to `WKWebView`

Also reported here https://github.com/react-native-community/react-native-webview/issues/819

**Comment by radko93** [comment]
Closing because it's located in https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/931

**Comment by amitworthee** [comment]
> When uploading a build today I got an email from Apple regarding the deprecation of `UIWebView`.
> 
> > ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs.
> 
> I found that the only library that still use `UIWebView` is `react-native-branch-deep-linking-attribution`. It has to be refactored to `WKWebView`
> 
> Also reported here [react-native-community/react-native-webview#819](https://github.com/react-native-community/react-native-webview/issues/819)

Got the same issue

**Comment by matthova** [comment]
Looks like the root issue was addressed in https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/932

Does this package require an update to consume the fix?

**Comment by matthova** [comment]
Ah, I was using the v2 api. I see that v3 and v4 are wrappers for the native code. If there are no plans to implement a similar fix for v2, a note should be added to the maintenance-v2 branch. Something to the effect of `"iOS will no longer support apps with branch v2, please upgrade"`.

Our app stil needs to migrate android to androidx so for the moment, we'll make the jump to branch v3 👍

**Comment by echo-branch** [comment]
This was fixed a while back.
