### ISSUE TITLE
Unable to use Branch SDK 0.28.1

### ISSUE THREAD

**Issue by TomSwift** [BranchMetrics/react-native-branch-deep-linking-attribution#498]
The new Branch SDK 0.28.1 removes the deprecated UIWebView, but this is unavailable to react-native-branch users.   

Because the react-native-branch pod spec specifies version 0.27.1 specifically it's not possible to incorporate Branch SDK 0.28.1.

It would be nice if we could get a release (soon!) of react-native-branch that relaxed the Branch SDK dependency to be '>= 0.27.1' or something.   At the very least, '0.28.1'.

**Comment by matthova** [comment]
I have a PR which bumps the version and addresses some build issues caused by the bumped version. https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/pull/497

**Comment by stianjensen** [comment]
As of https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases/tag/v4.2.1, this should be solved.
