### ISSUE TITLE
No visible @interface for 'Branch' declares the selector 'setAppleSearchAdsDebugMode'

### ISSUE THREAD

**Issue by marudy** [BranchMetrics/react-native-branch-deep-linking-attribution#504]
Hey guys,

When upgrading Branch iOS SDK to v `0.28.1` or `0.29.0` with CocoaPods I get the following issue:

<img width="411" alt="Screenshot 2019-09-28 at 18 44 33" src="https://user-images.githubusercontent.com/16783589/65819518-45407e80-e226-11e9-9110-22676837cf0e.png">

If I remove method `setAppleSearchAdsDebugMode` from from file `RNBranch.m`, the app manages to build. Also and according to [version history docs](https://docs.branch.io/version-histories/ios-version-history/), in version 0.28.1 there is the following change that looks related: `Remove Apple Search Ads debug which is redundant with Apple's existing debug.`

I'm working with the following versions:
- React Native: 0.59.9
- React Native Branch: 3.1.1
- Branch iOS SDK: 0.27.0 and trying to upgrade to 0.28.1 or 0.29.0 without success

**Comment by echo-branch** [comment]
That API was removed in 0.28.1.  Finally working on an update for RN.  We've been a bit resource short with several devs out.

**Comment by Audace** [comment]
I'm running into the same issue.

**Comment by Audace** [comment]
What is the work around for this right now? Is there a way to test without shipping a build to the app store?

**Comment by echo-branch** [comment]
@Audace Are you trying to test Apple Search Ads?  

Apple will return a dummy payload to all dev and testflight builds.  You should get a callback from branch with this dummy data.  It is not possible to test beyond that without going all the way to app store.

Newer versions of the Branch iOS also provides an option to ignore this test payload.

**Comment by echo-branch** [comment]
Fixed a while back.
