### ISSUE TITLE
Docs missing Obj C snippet for Branch/Firebase integration. Swift to Obj C translation needed.

### ISSUE THREAD

**Issue by samzmann** [BranchMetrics/react-native-branch-deep-linking-attribution#507]
Hi, I have a problem with iOS attributions not being passed to Firebase. I contacted support and was told I should add the following snipped to my AppDelegate.m.

The snippet is in Swift but my iOS project is in Objective C. So I need to convert it, but I have no knowledge of Obj C... And Branch support said there was no Obj C version of this code available :(

Is anyone here knowledgable enough to provide and translation Swift -> Obj C?

Here is the snippet, taken from the [Branch/Firebase integration docs](https://docs.branch.io/integrations/google-firebase/#ios):

```Swift
FirebaseApp.configure()
Branch.getInstance().initSession(launchOptions: launchOptions) { (params, error) in
    // do stuff with deep link data (nav to page, display content, etc)
    if(error == nil && params != nil){
        // create and add properties that you want to track in Firebase                
        var firebase_params = [String: Any]()
        firebase_params["clicked_branch_link"] =  params?["+clicked_branch_link"] ?? ""
        // get the click timestamp
        firebase_params["click_timestamp"] = params?["+click_timestamp"] ?? ""
        // get the link OG title  
        firebase_params["link_title"] = params?["$og_title"] ?? ""
        // get the link OG image  
        firebase_params["link_image"] =  params?["$og_image_url"] ?? ""
        // get the link campaign  
        firebase_params["utm_campaign"] = params?["~campaign"] ?? ""
        // get the link channel  
        firebase_params["utm_medium"] = params?["channel"] ?? ""
        // get the link feature  
        firebase_params["utm_source"] = params?["~feature"] ?? ""
        // check if this is an open or and install event
        if(UserDefaults.standard.object(forKey: "is_first_session") == nil){
        UserDefaults.standard.set(true, forKey: "is_first_session")
    }
    else{
        UserDefaults.standard.set(false, forKey: "is_first_session")
    }
    let event_name = UserDefaults.standard.bool(forKey: "is_first_session") == true ? "branch_install" : "branch_open"
    // track the event to Firebase
    Analytics.logEvent(event_name, parameters: firebase_params)
    }
}
```

**Comment by echo-branch** [comment]
Roughly.

`

    [[Branch getInstance] initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary * _Nullable params, NSError * _Nullable error) {
        if (!error && params) {
            NSMutableDictionary *firebaseParams = [NSMutableDictionary new];
            firebaseParams[@"clicked_branch_link"] = params[@"+clicked_branch_link"] ? params[@"+clicked_branch_link"] : @"";
            // repeat for each in the example
            
            if ([[NSUserDefaults standardUserDefaults] objectForKey:@"is_first_session"] == nil) {
                [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"is_first_session"];
            }
        } else {
            [[NSUserDefaults standardUserDefaults] setBool:NO forKey:@"is_first_session"];
        }
        
        NSString *eventName = [[NSUserDefaults standardUserDefaults] boolForKey:@"is_first_session"] ? @"branch_install" : @"branch_open";

        // log eventName and firebaseParams to firebase
    }];

`

**Comment by LaVielle** [comment]
@echo-branch Thanks for the reply.
I tried your code, builds fine but then my deeplinks don't work anymore. Why..?

I slightly modified your code (see bellow): modified the location of firebaseParams to be initialized before the if/else, but I doubt thats a problem.

Branch still notices that some link is opening the app, but the data I expect to find in the link is absent:

This is what I expect:

<img width="734" alt="Screen Shot 2019-10-22 at 5 01 40 PM" src="https://user-images.githubusercontent.com/22463797/67300409-30d26780-f4ee-11e9-8231-35f0480d1594.png">

This is what I get:

<img width="743" alt="Screen Shot 2019-10-22 at 4 56 19 PM" src="https://user-images.githubusercontent.com/22463797/67300423-362fb200-f4ee-11e9-98f8-d67fcdf18749.png">

Here is the whole piece of code I added in AppDelegate.m, slightly modified:

```ObjectiveC
    [[Branch getInstance] initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary * _Nullable params, NSError * _Nullable error) {
      
      NSMutableDictionary *firebaseParams = [NSMutableDictionary new];
      
      if (!error && params) {
        firebaseParams[@"clicked_branch_link"] = params[@"+clicked_branch_link"] ? params[@"+clicked_branch_link"] : @"";
        firebaseParams[@"click_timestamp"] = params[@"+click_timestamp"] ? params[@"+click_timestamp"] : @"";
        firebaseParams[@"link_title"] = params[@"+og_title"] ? params[@"+og_title"] : @"";
        firebaseParams[@"link_image"] = params[@"+og_image_url"] ? params[@"+og_image_url"] : @"";
        firebaseParams[@"utm_campaign"] = params[@"+~campaign"] ? params[@"+~campaign"] : @"";
        firebaseParams[@"utm_medium"] = params[@"+channel"] ? params[@"+channel"] : @"";
        firebaseParams[@"utm_source"] = params[@"+feature"] ? params[@"+feature"] : @"";
            
        if ([[NSUserDefaults standardUserDefaults] objectForKey:@"is_first_session"] == nil) {
          [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"is_first_session"];
        }
      } else {
        [[NSUserDefaults standardUserDefaults] setBool:NO forKey:@"is_first_session"];
      }
        
      NSString *eventName = [[NSUserDefaults standardUserDefaults] boolForKey:@"is_first_session"] ? @"branch_install" : @"branch_open";

      // log eventName and firebaseParams to firebase
      [FIRAnalytics logEventWithName:eventName parameters:firebaseParams];
    }];
```

**Comment by mpoozd** [comment]
@LaVielle 

does the code work with you ? 
I'm having same issue

**Comment by LaVielle** [comment]
@mpoozd 
Nope, it's not working... As mentioned above, it builds fine but then deeplinks don't work :/

**Comment by echo-branch** [comment]
We recently updated the RN SDK to address some long standing issues.  Could you check if the issue still occurs with the new SDK?  Thank you.

**Comment by derrick-branch** [comment]
@LaVielle can you update and see if this is still an issue? Otherwise can we close this out for now?
