### ISSUE TITLE
iOS: Branch SDK 0.29.0 + RN >= 60

### ISSUE THREAD

**Issue by wkoutre** [BranchMetrics/react-native-branch-deep-linking-attribution#509]
```
    OS: macOS Mojave 10.14.6
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
    Memory: 10.20 GB / 64.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.0 - ~/.yarn/bin/yarn
    npm: 6.10.2 - ~/.npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
  npmGlobalPackages:
    eslint-plugin-react-native: 3.6.0
    metro-react-native-babel-preset: 0.51.1
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-debugger-open: 0.3.19
    react-native-git-upgrade: 0.2.7
```

I recently upgraded my project to `react-native@0.61.1`, and `react-native-branch@4.2.0`. After updating pods, cleaning the iOS project, and successfully rebuilding, upon running the app (on an iPhone 11 simulator), I get the following error:

```
Please use v. 0.28.1 of Branch. In your Podfile: pod 'Branch', '0.28.1'. Then pod install.

+[RNBranch setupBranchInstance:]
    RNBranch.m:82
__18+[RNBranch branch]_block_invoke
_dispatch_client_callout
_dispatch_once_callout
+[RNBranch branch]
+[RNBranch setDebug]
-[AppDelegate application:didFinishLaunchingWithOptions:]
-[UIApplication(OneSignalReactNative) oneSignalApplication:didFinishLaunchingWithOptions:]
-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
-[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]
-[UIApplication _runWithMainScene:transitionContext:completion:]
-[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]
_UIScenePerformActionsWithLifecycleActionMask
__101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
-[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
-[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
__186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke_2
+[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
_UISceneSettingsDiffActionPerformChangesWithTransitionContext
__186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
_UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext
-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
__64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
-[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
-[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
-[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
-[FBSSceneImpl _callOutQueue_agent_didCreateWithTransitionContext:completion:]
__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke.154
-[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
__86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke
_dispatch_client_callout
_dispatch_block_invoke_direct
__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
-[FBSSerialQueue _queue_performNextIfPossible]
-[FBSSerialQueue _performNextFromRunLoopSource]
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
__CFRunLoopDoSource0
__CFRunLoopDoSources0
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

Since the [podspec at the root of the latest version of `react-native-branch` published to npm](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/react-native-branch.podspec) (`yarn add react-native-branch`) contains `s.dependency 'Branch', '0.29.0'`, adding `pod 'Branch', '0.28.1'` to my project's Podfile doesn't suffice.

Instead, it needs to be done in the aforementioned [podspec](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/react-native-branch.podspec).

Unless I'm missing something (very probable!), I'll most likely revert to a small script to replace `s.dependency 'Branch', '0.29.0'` with `s.dependency 'Branch', '0.28.1'` until `0.29.0` is confirmed to be working in the environment noted above.

Any input is greatly appreciated!

**Comment by echo-branch** [comment]
Yea.  I missed that while merging.  Pushing out a patch to fix it.

**Comment by wkoutre** [comment]
Sweet, thanks @echo-branch

**Comment by lucasroca** [comment]
I also recently upgraded my project to `react-native@0.61.2` and `react-native-branch@4.2.1`. I am getting `Please use v. 0.27.0 of Branch. In your Podfile: pod 'Branch', '0.27.0'. Then pod install.` I've tried cleaning xcode project, cleaning the packager cache, pod deintegrate and pod install again, but still get the error. Could you advice me here?

**Comment by wkoutre** [comment]
@lucasroca 

`"update-pods": "cd ios && rm -f Podfile.lock && pod update && cd .."`

**Comment by echo-branch** [comment]
@lucasroca You're getting an older version of the Branch plugin.  Try updating the react-native-branch@4.2.1

**Comment by lucasroca** [comment]
It was indeed a caching issue. I ended up deleting the Pods and build directories and also the Podfile.lock, then installed pods again and the error was gone. Thanks you two.

**Comment by jacobcabantomski-ct** [comment]
Ran into same issue, was able to resolve with `pod install --repo-update`. Thanks for comments above, made issue easier to dig into 👍

**Comment by sergeymorkovkin** [comment]
@echo-branch, I think we should allow ">= 0.29.0" without specifying strict version in podspec. Otherwise it's not possible to upgrade to the most recent version.

**Comment by echo-branch** [comment]
@sergeymorkovkin 
I'm not able to easily do that.  Once we get a new maintainer on-boarded we'll update React Native in a more timely manner.

Long answer.  React Native autolinks the native plugin and pulls the exact version string from our podspec.  podspecs are not allowed to have inexact version numbers.

**Comment by sergeymorkovkin** [comment]
@echo-branch
Hm, maybe at least upgrade to 0.29.3?

**Comment by sergeymorkovkin** [comment]
>  podspecs are not allowed to have inexact version numbers.

Can't confirm. [Here is an example](https://github.com/CleverTap/clevertap-react-native/blob/master/clevertap-react-native.podspec#L21) or version pattern.

**Comment by echo-branch** [comment]
@sergeymorkovkin 
Yea, I was mistaken.  The error is on our side, not that pods doesn't allow it.  Either way, changing just the podspec isn't sufficient to get it to work properly.  There is a ticket to revisit this.

**Comment by echo-branch** [comment]
Should be fixed in the latest release.
