### ISSUE TITLE
React/RCTLog.h' file not found

### ISSUE THREAD

**Issue by dinesh-rudra** [BranchMetrics/react-native-branch-deep-linking-attribution#510]
//
//  RNBranchConfig.m
//  Pods
//
//  Created by Jimmy Dee on 6/7/17.
//
//

**#import <React/RCTLog.h>** (here i am getting React/RCTLog.h file not found).

#import "RNBranchConfig.h"

NSString * _Nonnull const RNBranchConfigDebuBuild core ReactgModeOption = @"debugMode";
NSString * _Nonnull const RNBranchConfigBranchKeyOption = @"branchKey";
NSString * _Nonnull const RNBranchConfigLiveKeyOption = @"liveKey";
NSString * _Nonnull const RNBranchConfigTestKeyOption = @"testKey";
NSString * _Nonnull const RNBranchConfigUseTestInstanceOption = @"useTestInstance";
NSString * _Nonnull const RNBranchConfigDelayInitToCheckForSearchAdsOption = @"delayInitToCheckForSearchAds";
NSString * _Nonnull const RNBranchConfigAppleSearchAdsDebugModeOption = @"appleSearchAdsDebugMode";
NSString * _Nonnull const RNBranchConfigDeferInitializationForJSLoadOption = @"deferInitializationForJSLoad";

@interface RNBranchConfig()
@property (nonatomic) NSDictionary *configuration;
@property (nonatomic, readonly) NSData *configFileContents;
@property (nonatomic) NSURL *configFileURL;
@end

@implementation RNBranchConfig

+ (RNBranchConfig * _Nonnull)instance
{
    @synchronized(self) {
        static RNBranchConfig *_instance;
        static dispatch_once_t once = 0;
        dispatch_once(&once, ^{
            _instance = [[RNBranchConfig alloc] init];
        });
        return _instance;
    }
}

- (instancetype)init
{
    self = [super init];
    if (self) {
        [self findConfigFile];
        [self loadConfigFile];
    }
    return self;
}

- (void)loadConfigFile
{
    NSData *data = self.configFileContents;
    if (!data) return;
    
    NSError *error;
    id object = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
    if (!object || error) {
        RCTLogError(@"Failed to parse branch.json. Error: %@", error.localizedDescription);
        return;
    }
    
    if (![object isKindOfClass:NSDictionary.class]) {
        RCTLogError(@"Contents of branch.json should be a JSON object.");
        return;
    }
    
    self.configuration = object;
}

- (NSData *)configFileContents
{
    if (!self.configFileURL) return nil;
    RCTLogInfo(@"Loading %@", self.configFileURL.pathComponents.lastObject);
    
    NSError *error;
    NSData *data = [NSData dataWithContentsOfURL:self.configFileURL options:0 error:&error];
    if (!data || error) {
        RCTLogError(@"Failed to load %@. Error: %@", self.configFileURL, error.localizedDescription);
        return nil;
    }
    return data;
}

- (void)findConfigFile
{
    if (self.configFileURL) return;
    
    __block NSURL *configFileURL;
    NSBundle *mainBundle = NSBundle.mainBundle;
    NSArray *filesToCheck =
    @[
#ifdef DEBUG
      @"branch.ios.debug",
      @"branch.debug",
#endif // DEBUG
      @"branch.ios",
      @"branch"
      ];
    
    [filesToCheck enumerateObjectsUsingBlock:^(NSString *  _Nonnull file, NSUInteger idx, BOOL * _Nonnull stop) {
        configFileURL = [mainBundle URLForResource:file withExtension:@"json"];
        *stop = (configFileURL != nil);
    }];
    
    if (!configFileURL) {
        RCTLogInfo(@"Could not find branch.json in app bundle.");
        return;
    }
    
    self.configFileURL = configFileURL;
}

- (BOOL)debugMode
{
    NSNumber *number = self[RNBranchConfigDebugModeOption];
    return number.boolValue;
}

- (BOOL)useTestInstance
{
    NSNumber *number = self[RNBranchConfigUseTestInstanceOption];
    return number.boolValue;
}

- (BOOL)delayInitToCheckForSearchAds
{
    NSNumber *number = self[RNBranchConfigDelayInitToCheckForSearchAdsOption];
    return number.boolValue;
}

- (BOOL)appleSearchAdsDebugMode
{
    NSNumber *number = self[RNBranchConfigAppleSearchAdsDebugModeOption];
    return number.boolValue;
}

- (BOOL)deferInitializationForJSLoad
{
    NSNumber *number = self[RNBranchConfigDeferInitializationForJSLoadOption];
    return number.boolValue;
}

- (NSString *)branchKey
{
    return self[RNBranchConfigBranchKeyOption];
}

- (NSString *)liveKey
{
    return self[RNBranchConfigLiveKeyOption];
}

- (NSString *)testKey
{
    return self[RNBranchConfigTestKeyOption];
}

- (id)objectForKey:(NSString *)key
{
    return self.configuration[key];
}

- (id)objectForKeyedSubscript:(NSString *)key
{
    return self.configuration[key];
}

@end

i have implemented the react-native-branch and after follow the steps to set up in ios, i am getting 'React/RCTLog.h' file not found.

Any input is greatly appreciated!

**Comment by dinesh-rudra** [comment]
i find out the issue and solved it by adding React path and some extra stuff in pod file and then go for pod install. it's working fine now.


# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoPhoxx' do
  

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'

 


 rn_path = '../node_modules/react-native'
 
 pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
 pod 'React', path: rn_path, subspecs: [
 'Core',
 'CxxBridge',
 'DevSupport',
 'RCTActionSheet',
 'RCTAnimation',
 'RCTGeolocation',
 'RCTImage',
 'RCTLinkingIOS',
 'RCTNetwork',
 'RCTSettings',
 'RCTText',
 'RCTVibration',
 'RCTWebSocket',
 ]
 pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
 
 post_install do |installer|
   installer.pods_project.targets.each do |target|
     if target.name == "React"
       target.remove_from_project
     end
   end
 end

  pod 'react-native-branch', :path => '../node_modules/react-native-branch'

end

**Comment by farhankassam2** [comment]
Hi @dinesh-rudra , I am facing the exact same error after trying to use `react-native-branch`. In the above solution, can you elaborate more specifically on what lines you uncommented or modified/added to remove this error? I am still confused as to how you went about solving the issue. Any help I appreciated. Thank you :).
