### ISSUE TITLE
 'react-native-branch/RNBranch.h' file not found

### ISSUE THREAD

**Issue by felixchan** [BranchMetrics/react-native-branch-deep-linking-attribution#511]
React Native 0.61.1
platform :ios, '9.0' (not using `use_frameworks`)

`yarn add react-native-branch` (installs 4.2.1)
`react-native link react-native-branch`
`cd ./ios; pod repo update; pod install`

Open .workspace, clean project, add objective-C code inside AppDelegate.m

` 'react-native-branch/RNBranch.h' file not found` while building

**Comment by echo-branch** [comment]
The import should be removed in newer react.  React Native automatically handles it.  Versions before 0.60 required it.

**Comment by felixchan** [comment]
@echo-branch  if I don't put `#import <react-native-branch/RNBranch.h> ` at the top of my AppDelegate.m, I get: `Use of undeclared identifier 'RNBranch'` in the following code:

```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    if (![RNBranch.branch application:app openURL:url options:options]) {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    }
    return YES;
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
    return [RNBranch continueUserActivity:userActivity];
}

```

**Comment by echo-branch** [comment]
Ah I misunderstood your question.

`#import <RNBranch/RNBranch.h>`

**Comment by rosiearms** [comment]
@felixchan I'm having the same issue, RN 61.3 and branch 4.1.0, did you find a solution to this?

**Comment by rosiearms** [comment]
just realise @echo-branch has provided the answer:

change to the import to
`#import <RNBranch/RNBranch.h>`
