### ISSUE TITLE
one_time_use

### ISSUE THREAD

**Issue by LydGol90** [BranchMetrics/react-native-branch-deep-linking-attribution#513]
Hi, not really an issue but I am struggling to find anything that says whether it is possible to create a one time use link using the react native SDK. In the branch docs there are various options such as setting 'type' to 1, or using the '$one_time_use' parameter but neither seems to have any effect for me. Any help would be greatly appreciated. Many thanks!

**Comment by derrick-branch** [comment]
@LydGol90 can you write into support@branch.io and provide the exact steps you're using to create a link, the resulting link, and your branch_key or app_id? Thanks!

Going to close this for now. Please re-ping here if Support is unable to resolve your issue.
