### ISSUE TITLE
Do we need to follow "Updating from an earlier version or starting with v3.0.0" ?

### ISSUE THREAD

**Issue by felixchan** [BranchMetrics/react-native-branch-deep-linking-attribution#515]
This is a question, not a bug.

I am installing from scratch, using create-react-native-app.

`"react-native-branch": "^4.2.1",`
`react-native: 0.61.1`

Do I need to follow instructions from [here](https://docs.branch.io/apps/react-native/#updating-from-an-earlier-version-or-starting-with-v300)?

**Comment by echo-branch** [comment]
Please contact our support team for integration questions.  The github issues pages are generally only monitored for probable bug reports.
