### ISSUE TITLE
Building with Android does not launch application due to android.name in Manifest

### ISSUE THREAD

**Issue by felixchan** [BranchMetrics/react-native-branch-deep-linking-attribution#516]
The application builds and installs, but it does not launch on the emulator.

When I launch the app manually, it crashes.

When I removed this: `android:name="com.eneff.branchandroid.CustomApplicationClass"` and replaced it with `android:name=".MainApplication"`, the app launches fine.   Furthermore, `myApp.app.link/code` does not launch my application.

How can I work around this?

**Comment by echo-branch** [comment]
Please contact our support team for help with integration.  The documentation is a bit out of date and we need to update it.  Sorry for the hassle.
