### ISSUE TITLE
Document "reserved" query parameters

### ISSUE THREAD

**Issue by npedrini** [BranchMetrics/react-native-branch-deep-linking-attribution#518]
For weeks now, I've been debugging an issue where one of my deep links worked while the other two didn't. After a ton of debugging it turns out that Branch was failing to recognize these two deep links as such because they included an `access_token` param in the query string (in my case, the deep links in question were used to verify resetting the user's password and deleting their account, hence the auth token).

Anyway, after closer inspection it turns out that one of the ways Branch determines if a deep link is a valid Branch link or not is by testing for a match against the following regex:

`^(?i).+:.*[?].*(password|o?auth|o?auth.?token|access|access.?token)`

So, if your deep link contains any of the above, deep linking will fail. 

This should be clearly documented in the README and Branch.io documentation!

**Comment by derrick-branch** [comment]
Sorry for the headache, and for the slow response @npedrini. We've created a ticket to update our docs. Internal ticket DOCS-1222. Thanks for raising this -- hoping we can save others this headache.
