### ISSUE TITLE
[Android] install_referrer is being deprecated

### ISSUE THREAD

**Issue by a-koka** [BranchMetrics/react-native-branch-deep-linking-attribution#522]
Google is deprecating support for `install_referrer` as of March 2020. Is there a plan in place to migrate to the [Play Install Referrer Library](https://developer.android.com/google/play/installreferrer/library.html) soon?

**Comment by echo-branch** [comment]
Yes.  There is a ticket for this on the Branch Android SDK board.

**Comment by shercoder** [comment]
Any update on this? Also is this new update will be supported for RN <=0.59.* as well or only for >0.60.*

**Comment by echo-branch** [comment]
My preference is to update both, however we are still looking for a full time RN maintainer.  

I am currently working on a maintenance update for 0.60+.   A corresponding maintenance release for <=0.59 might take some time.

**Comment by adiwon9555** [comment]
Any update on this?
By when can we expect this feature to be integrated?

**Comment by echo-branch** [comment]
For 0.60+ this is addressed in the latest release.  For 0.59 or earlier, we don't have an update yet.

**Comment by martinalderson** [comment]
Hi, is there any update on this matter? It is March very soon. We are on 0.59 and would prefer to patch that version while we look to upgrade our RN stack.

**Comment by RoboTeddy** [comment]
Does this mean attribution won't work with AppsFlyer for RN apps < 0.59 come March 1?

**Comment by echo-branch** [comment]
@jdee is working on an update

**Comment by RoboTeddy** [comment]
@echo-branch @jdee awesome, thank you both!

if we don't get this update in time (or neglect to update to it), will attribution stop working entirely on android, or just become less reliable?

**Comment by derrick-branch** [comment]
@jdee can you post an update?

**Comment by jdee** [comment]
This was released as 3.1.2 for RN < 0.60 with Android 4.3.2 and iOS 0.31.3.
