### ISSUE TITLE
Switch to play referrer API by march 1, 2020

### ISSUE THREAD

**Issue by TeamDlxx** [BranchMetrics/react-native-branch-deep-linking-attribution#524]
I received this email from google store 

"Switch to play referrer API by march 1, 2020"

![issue](https://user-images.githubusercontent.com/52232678/70789574-15306280-1db5-11ea-9397-5ce636b2060f.png)

So I was looking in code and got this referrer receiver. so I was thinking that's issue, so please help me to understand the actual problem.

<img width="942" alt="Screenshot 2019-12-13 at 2 29 04 PM" src="https://user-images.githubusercontent.com/52232678/70789531-034ebf80-1db5-11ea-9d09-7d5abf6d238f.png">

**Comment by echo-branch** [comment]
This is on the Android SDKs backlog.

**Comment by TeamDlxx** [comment]
Sorry I did not get your point.
Actually I want to know that the reason is react-native-branch on the android side?

**Comment by csalmi-branch** [comment]
@TeamDlxx This message is due to the android SDK using the play install referrer API. So yes, its react-native-branch on the android side. We will be providing an updated SDK soon.

**Comment by martintreurnicht** [comment]
is this not resolved by https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases/tag/v4.3.0?

**Comment by echo-branch** [comment]
Yes, that release addresses this issue.
