### ISSUE TITLE
Error from Branch: The network request was invalid.

### ISSUE THREAD

**Issue by Sohadwd** [BranchMetrics/react-native-branch-deep-linking-attribution#528]
I've got this error after add branch to my code `Error from Branch: The network request was invalid.`

<img width="743" alt="Screen Shot 2020-01-08 at 8 56 23 AM" src="https://user-images.githubusercontent.com/28750873/71956824-cd0a3180-31f4-11ea-9dd9-4d73e96deb64.png">

and when I make a share from the app, it's generate a strange link, this's `https://bnc.lt/a/key_test_yyyy?channel=WhatsApp&feature=share&type=0&duration=0&source=ios&data=eyJpZCI6IjV0NHFsRE5uRlBNWW9pMU96SVF0IiwiJG9nX2Rlc2NyaXB0aW9uIjoi2KfZhti22YXZiNinINmE2Yog2YHZiiAg2KrYrNix2KjYqSB0ZXN0IG1pbmltdW1tIHNlYXRzINmB2YogTWFra2FoINmK2YjZhSAyMDIwLzAxLzA5INi52YTZiSDZhdmG2LXYqSDYs9io2YTZgdiqIPCfjoggIiwiJGNhbm9uaWNhbF9pZGVudGlmaWVyIjoiRXhwZXJpZW5jZSIsInR5cGUiOiJleHBlcmllbmNlIn0%3D` 

and when I try to open it, I got this result!
![IMG_9129](https://user-images.githubusercontent.com/28750873/71959027-6ab42f80-31fa-11ea-9413-d9cf4d2414ed.PNG)

# Environment
react-native: 0.59.8
react-native-branch: ^3.0.0-beta.1
 

# Any Help on this, please?!

**Comment by echo-branch** [comment]
That's a long link usually generated when there is a network connectivity issue.  The issue should not happen regularly.

On a side note, we haven't updated the older 3.x series yet, so it could be a bug there.  It may be a bit of time before we get this prioritized to really dig into.

**Comment by klaaz0r** [comment]
@echo-branch We are running below react native 0.60 so we are depended on this, any updates?

**Comment by Sohadwd** [comment]
Yes, the reason returns to file **branch.json** in the Xcode, I've put all the info on it and then works fine! 

<img width="520" alt="Screen Shot 2020-05-16 at 4 59 07 PM" src="https://user-images.githubusercontent.com/28750873/82121552-a78ac700-9796-11ea-8581-04b502646f12.png">

Not depending on react native version.

**Comment by octobus55** [comment]
I was having the same issue and found out that there was a problem with accessing the keys in my environment files with react-native-config. If you are having this problem just enableLogging and check your logs, the logs are more detailed so it's easier to detect the main problem.
