### ISSUE TITLE
Branch only registers link correctly when app is killed. /Documentation out of date

### ISSUE THREAD

**Issue by jste7102** [BranchMetrics/react-native-branch-deep-linking-attribution#529]
I am trying to integrate 'react-native-branch@^4.2.1 into a detached expo 36 app which relies on react native 61.4 and I have followed the documentation on npm and branch.io.  I'm running into an issue where params are correct in branch.subscribe if the app is launched on branch link click on android, but if the app is coming from the background to the foreground params.+'clicked_branch_link" is false.  I've tried linking and unlinking, adding a branch.json file to my configs, and other tweaking of the android configs and I haven't found anything that fixes this.

Additionally, I still need to 'react-native-link' and use the RNBranchPackage() in MainApplication.java to get anything to work.  Otherwise when I import branch into the RN code the object is undefined and I get this error https://github.com/expo/expo/issues/5349.  I am on expo 36 so I am not using the expo version of branch as that was removed as documented here https://github.com/expo/expo/blob/master/CHANGELOG.md#3600.

Additionally, the steps recommended [here](https://www.npmjs.com/package/react-native-branch) for installing 4.0.0+ for Branch are not on [the main website](https://docs.branch.io/apps/react-native/), and it's confusing to know what to follow, some of them are contridictory as well, for example, do you use '  Branch.getAutoInstance(this);' or  'RNBranchModule.getAutoInstance(this);' in the MainApplication.java function? In any case I've tried both and neither work.

**Comment by echo-branch** [comment]
We are working on a RN update including a documentation cleanup.

I think you're getting an older version of the underlying Android SDK with expo and that's conflicting with the instructions for the newer version.  I'll make a ticket to see if we can repro the situation.

**Comment by jste7102** [comment]
Sounds good,

Yeah the documentation is in a bad state right now.  We had to dig through the branch source code and got it working eventually by adding this onNewIntent function and initializing super after setting the intent.  

  @Override
  public void onNewIntent(Intent intent) {
      setIntent(intent);
      super.onNewIntent(intent);
  }

**Comment by markmoomoo** [comment]
same problem, MainActivity and MainApplication followed the documentation, with react-native-branch 5.0.0-rc, Android app background and click the link to start the app got only {"+is_first_session":false,"+clicked_branch_link":false}
our project is not expo, but a React-native-init project, with RN 0.60.6

**Comment by markmoomoo** [comment]
Got the reason why I only got  {"+is_first_session":false,"+clicked_branch_link":false} at android, when I start from the branch.XXX.com?token=<userToken>, it first bring us to the playstore, and then user press open to open the app, which would logout full params with {"+is_first_session":false,"+clicked_branch_link":false, "token": <user_token>}.
However, if pertime, we only start from the playstore open app without getting it from the very beginning of the branch.xxx.com?token= , we will only get the  {"+is_first_session":false,"+clicked_branch_link":false}, that's why our params.token was missing
