### ISSUE TITLE
Device fingerprint/ID not received in webhook payload

### ISSUE THREAD

**Issue by poocart** [BranchMetrics/react-native-branch-deep-linking-attribution#533]
Hey, it seems that even though device ID/fingerprint can be retrieved in JS side (with last/first refer params) those are not received in Branch.io controlled webhooked event (`INSTALL`, `OPEN`, etc.) payload's `user_data`.

Is there anything additional that needs to be setup to retrieve those with Branch.io webhooked events?

Having this for both iOS and Android.

**Comment by derrick-branch** [comment]
@poocart can you write into support@branch.io and specify exactly which key-value pairs you're not seeing in the webhooks payload? Please be sure to include a branch_key or app_id as well. Thank you.
