### ISSUE TITLE
[[Branch getInstance] delayInitToCheckForSearchAds] causes app to hang

### ISSUE THREAD

**Issue by Audace** [BranchMetrics/react-native-branch-deep-linking-attribution#534]
We followed the instructions in the [Apple Search Ads docs](https://docs.branch.io/deep-linked-ads/apple-mobile-tracking/) by Branch. After shipping this live, we ran into a problem where the app would load indefinitely on a white screen for some users.

Generally, upon initial download the app would launch fine. However, if a user had killed the app and opened it, they would be confronted with a white screen indefinitely. If the user backgrounded the app and then foregrounded it, the app would load and work fine.

This issue was resolved by _removing_ `[[Branch getInstance] delayInitToCheckForSearchAds]` from `AppDelegate.m`. 

Two questions:
1) Why is this happening? It seems like the `delay` is indefinite and not timing out?
2) How can we attribute users from Apple Search Ads without terribly impacting performance?

We're using `"react-native-branch"`: `"4.2.0"`.

**Comment by echo-branch** [comment]
Working on a RN update that will bring a significant refactor of the Apple Search Ads behavior.  I'd like to see if an updated SDK resolves the issue.

**Comment by Audace** [comment]
Any idea of the ETA? We were forced to turn Apple Search Ads off 😞

**Comment by echo-branch** [comment]
It's in the current sprint, so hopefully in the next week or two.

**Comment by Audace** [comment]
This seems to be resolved by 4.3.0. Thanks.
