### ISSUE TITLE
Links created with generateShortUrl do not have custom metadata attached.

### ISSUE THREAD

**Issue by jpramassini** [BranchMetrics/react-native-branch-deep-linking-attribution#536]
We are currently using the `createBranchUniversalObject` to create links with metadata attached. We then create short links with the `generateShortUrl` method of the Universal Object. However, when we then try to consume those links with `Branch.subscribe` the bundle has no metadata attached and has `+clicked_branch_link: False`. In the past this field has had a `true` value. The `error` field is false as well.

We have used the current code for about 5 months and have not had this issue before. This issue began happening recently, about 3 days ago.

Edit: We're using version `4.2.0`.

**Comment by akshayguptaquovantis** [comment]
Any update on this?
