### ISSUE TITLE
No visible @interface for 'Branch' declares the selector 'registerPluginName:version:'

### ISSUE THREAD

**Issue by Audace** [BranchMetrics/react-native-branch-deep-linking-attribution#538]
After upgrading to version 4.3.0, I get this error when attempting to build for iOS. I haven't changed anything about the `AppDelegate.m`.

**Comment by a-koka** [comment]
How did you fix this @Audace ?

**Comment by Thomazella** [comment]
Running into this bug, commenting the line for now. @Audace did you fix it?
![Screen Shot 2020-04-03 at 10 33 40 PM](https://user-images.githubusercontent.com/15015324/78415957-924d4500-75fb-11ea-9b23-c67b0b93cee3.png)

**Comment by jdee** [comment]
@Thomazella The short answer is I don't know how this could happen without a lot more detail. Can you please contact support@branch.io if you continue to have trouble, and we'll get it sorted out? Thanks.

**Comment by MrAlekhin** [comment]
@jdee having the same issue.
**react-native: 0.59.0**
Steps i did:
- npm install react-native-branch@^3.0.0
- react-native link l react-native-branch
- pod init
- my Podfile
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevOneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for DevOneSignalNotificationServiceExtension
end

target 'fitcompete' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'
  # Pods for fitcompete
  pod 'Branch', '0.28.1'

  target 'fitcompeteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fitcompeteDev' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'
  # Pods for fitcompeteDev
  pod 'Branch', '0.28.1'
end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for OneSignalNotificationServiceExtension

end
```

**Comment by MrAlekhin** [comment]
> @jdee having the same issue.
> <img alt="Screen Shot 2020-06-21 at 2 13 16 AM" width="1276" src="https://user-images.githubusercontent.com/24749983/85218090-d9c6b000-b364-11ea-9c21-4fad47fcc93f.png">
> 
> **react-native: 0.59.0**
> Steps i did:
> 
> * npm install react-native-branch@3.2.1
> * react-native link  react-native-branch
> * pod init
> * pod install
>   my Podfile:
> 
> ```
> # Uncomment the next line to define a global platform for your project
> # platform :ios, '9.0'
> 
> target 'DevOneSignalNotificationServiceExtension' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for DevOneSignalNotificationServiceExtension
> end
> 
> target 'fitcompete' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   # use_frameworks!
>   platform :ios, '9.0'
>   # Pods for fitcompete
>   pod 'Branch', '0.28.1'
> 
>   target 'fitcompeteTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
> end
> 
> target 'fitcompeteDev' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   # use_frameworks!
>   platform :ios, '9.0'
>   # Pods for fitcompeteDev
>   pod 'Branch', '0.28.1'
> end
> 
> target 'OneSignalNotificationServiceExtension' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for OneSignalNotificationServiceExtension
> 
> end
> ```

okay looks like I've found some workaround but still would be nice if @jdee can take a look 🙏
if I am downgrading `react-native-branch` version to `3.2.0` it seems working. At least I got a successful build. So looks like an issue is with `3.2.1` branch version with `registerPluginName` method
