### ISSUE TITLE
Upgrade from 4.2.1 -> 4.3.0 causing native crashes on Android

### ISSUE THREAD

**Issue by AndrewMorsillo** [BranchMetrics/react-native-branch-deep-linking-attribution#539]
After upgrading from 4.2.1 to 4.3.0 Branch is crashing on new installs of my app in production. Here is the stack trace:

I have multidex enabled.

```
java.lang.RuntimeException: Unable to instantiate receiver io.branch.referral.InstallListener: 
java.lang.ClassNotFoundException: Didn't find class "io.branch.referral.InstallListener" on path:
 DexPathList[[zip file "/data/app/com.myteam.myapp-zgPIg187Ny9U2fA1THFCpA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myteam.myapp-zgPIg187Ny9U2fA1THFCpA==/lib/arm64, /data/app/com.myteam.myapp-zgPIg187Ny9U2fA1THFCpA==/base.apk!/lib/arm64-v8a, /system/lib64]]
```

I'm guessing this intent receiver was removed and it never got noted in the docs?
From AndroidManifest.xml
```
      <!-- Branch install referrer tracking (optional) -->
        <receiver android:name="io.branch.referral.InstallListener" android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
```

React native info:

```
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 4.30 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
```

**Comment by echo-branch** [comment]
This change was communicated via email to all clients. 

The react native readme update is still in progress and not up to date with this change.  Sorry for the confusion.

**Comment by blueberry6401** [comment]
> This change was communicated via email to all clients.
> 
> The react native readme update is still in progress and not up to date with this change. Sorry for the confusion.

So how to fix this? Just remove receiver "io.branch.referral.InstallListener" and it's still functional, right?

**Comment by blueberry6401** [comment]
And the only email I received from branch is this one
![image](https://user-images.githubusercontent.com/7337535/74019913-0fc55200-49cb-11ea-9728-2e3193a90b6e.png)

**Comment by blueberry6401** [comment]
And the only email I received is this one
![image](https://user-images.githubusercontent.com/7337535/74019955-28ce0300-49cb-11ea-96b8-fe1abedd6128.png)

**Comment by echo-branch** [comment]
@blueberry6401 
It was a different email, but to summarize Google will stop broadcasting install_referrer intents soon and we require the AndroidManifest to be modified to remove the InstallListener block.  Which you've already figured out.

**Comment by echo-branch** [comment]
Closing as user figured out the issue.
