### ISSUE TITLE
dismissing dialog when calling showShareSheet crashes

### ISSUE THREAD

**Issue by jackiewung** [BranchMetrics/react-native-branch-deep-linking-attribution#540]
to reproduce:
- call showShareSheet
- click send to message, but don't send
- close message
- close sheet

see error:
![IMG_7350](https://user-images.githubusercontent.com/34897095/73999363-640ff980-4919-11ea-98c1-bdd376ec56b7.PNG)

using v4.3.0

**Comment by echo-branch** [comment]
Confirmed issue as described.  Looking into a fix.
