### ISSUE TITLE
Android app not working with React navigation, app crashed each time run the app.

### ISSUE THREAD

**Issue by PankajPrajapati** [BranchMetrics/react-native-branch-deep-linking-attribution#544]
I have followed official instruction which is given [here](https://help.branch.io/developers-hub/docs/react-native#section-configure-app) to implement deep linking in my react native project. My project also contains [react-navigation](https://reactnavigation.org/docs/4.x/getting-started) and before adding deep linking it was working fine. Now after adding deep linking when I try to run the android app it always crashed.

After spending a lot of time, I found that If I remove anyone library from these two, my android app runs well. I tried to find the root cause of this issue and I found that when I install [react-native-screens](react-native-screens) which is required by the react-navigation application is not working.

I don't know what is wrong with these two frameworks, if I remove deep linking library then it's also working fine.

I tried with one more demo and it's happening the same in the demo project as well.

This is my react native environment details.

System:
    OS: macOS 10.15.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 48.21 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    npm: 6.13.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Please let me know if you require more details.

**Comment by rabindrachhachan** [comment]
The same issue happening to me. Any workaround so far?

**Comment by gdeluna-branch** [comment]
For integration issues please open a ticket with support: https://help.branch.io/using-branch/page/submit-a-ticket
