### ISSUE TITLE
Branch.subscribe() only triggers for non branch link

### ISSUE THREAD

**Issue by shaheryar-ahmad** [BranchMetrics/react-native-branch-deep-linking-attribution#546]
I have been stuck at this issue for an entire day now and can't seem to find a solution. Branch.subscribe() is only getting triggered at non-branch deep links that are. Branch deep link will only open the app, but Branch.subscribe() just never gets triggered. I'm using Expo SDK36. I've tried testing out the app with Firebase Dynamic Links and they seem to work perfectly.  Please help!

**Comment by jdee** [comment]
We'll be happy to help you. Can you please contact support@branch.io to open a ticket and provide more detail, in particular:
- What version of react-native-branch are you using?
- Is this happening on Android or iOS or both?
- An example link that does not work.
- Any further detail on your environment and/or testing.

Thank you.
