### ISSUE TITLE
Link is not clickable in Redme Note 5 v8.1.0, iPhone 7 Plus v13.3

### ISSUE THREAD

**Issue by girishchauhan-info** [BranchMetrics/react-native-branch-deep-linking-attribution#547]
**SDK Version :**
"react-native-branch": "4.2.1",
**Issue :** 
When we generate a link and share via builtin android/iOS message app. Link is **not clickable**.

**Note:**
It works on other devices.

`this.branchUniversalObject.generateShortUrl(linkProperties, controlParams);`

![Redme message copy](https://user-images.githubusercontent.com/61869858/76076482-fc56d800-5fc4-11ea-9cc6-7bbd0233da45.jpg)
![iPhone 7plus-link copy](https://user-images.githubusercontent.com/61869858/76076642-3e801980-5fc5-11ea-8aad-b9a85c4a9a4c.PNG)

**Comment by jdee** [comment]
I'm not sure what would cause this. Is there any difference if you type or paste only the URL directly without the share text? As long as the message app recognizes a URL, it will usually make a clickable link. That should have nothing to do with Branch.

Have you seen webview_example in this repo? Here is an example of sharing a link from a BUO.

https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/examples/webview_example/src/Article.js#L73

You can also improve your preview in the message app or anywhere that previews (Slack, social media) by setting the title, contentDescription and contentImageUrl:

https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/examples/webview_example/src/Article.js#L41

If this doesn't help or you cannot resolve the issue, can you please contact support@branch.io with more detail? Perhaps you can share with us a link that doesn't work, and we can try to see why.

Thank you.
