### ISSUE TITLE
Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by urtheone** [BranchMetrics/react-native-branch-deep-linking-attribution#549]
Branch RN sdk update to 3.1.2 few days ago, after i change it to 3.1.2,crash happend. on 3.1.1 ，There is no problem. 
I have change android native sdk to 4.3.2.

java.lang.NullPointerException

Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference

解析原始
1 io.branch.rnbranch.RNBranchModule$1.a(RNBranchModule.java:132)
2 io.branch.referral.Branch.a(Branch.java:2608)
3 io.branch.referral.Branch.a(Branch.java:1430)
4 io.branch.referral.Branch.a(Branch.java:1099)
5 io.branch.rnbranch.RNBranchModule.initSession(RNBranchModule.java:118)
6 io.branch.rnbranch.RNBranchModule.initSession(RNBranchModule.java:111)
7 com.shangri_la.business.main.MainActivity.v(MainActivity.java:227)
8 com.shangri_la.business.main.MainActivity.onStart(MainActivity.java:217)
9 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
10 android.app.Activity.performStart(Activity.java:7252)
11 android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
12 android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
13 android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
14 android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
15 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
16 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
17 android.os.Handler.dispatchMessage(Handler.java:106)
18 android.os.Looper.loop(Looper.java:201)
19 android.app.ActivityThread.main(ActivityThread.java:6806)
20 java.lang.reflect.Method.invoke(Native Method)
21 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
22 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by jdee** [comment]
This NPE has been fixed in release 3.2.0 of `react-native-branch`. If you update to that version and encounter an error, please report the error to support@branch.io and we'll address it. Thanks!
