### ISSUE TITLE
Setup documentation out-of-sync (Branch.io vs. GitHub)

### ISSUE THREAD

**Issue by edreyyo** [BranchMetrics/react-native-branch-deep-linking-attribution#553]
Hi,

It's a bit difficult following your setup instructions because the documentation on your website and on GitHub are out-of-sync and give different instructions.

For example, the Android setup instructions [on your website](https://help.branch.io/developers-hub/docs/react-native#section-android) say:

![branch](https://user-images.githubusercontent.com/6125211/76533591-9b257d80-6478-11ea-987c-11088e6cd41b.png)

While the [instructions on GitHub](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/docs/version-4.md#autolinking) say:

![github](https://user-images.githubusercontent.com/6125211/76533613-a37db880-6478-11ea-9747-ba3bbf0fb6f6.png)

Could these please be updated?

**Comment by gdeluna-branch** [comment]
The docs have undergone some changes since this was opened. Please open a new ticket if there is still any confusion.
