### ISSUE TITLE
React native branch not working on Chrome iOS

### ISSUE THREAD

**Issue by Seb-AS** [BranchMetrics/react-native-branch-deep-linking-attribution#555]
Hi, I've an issue on Chrome IOS(latest version), deferred deep linking and deep linking it's not working, but works as expected using the same link on safari.

I already sent multiple emails in the last 15 days with the repro(videos/screenshoots) to support but I did not get any answers.

I'm on the latest branch version and iOS. 

Thanks

**Comment by Seb-AS** [comment]
is branch dead?

**Comment by derrick-branch** [comment]
@Seb-AS can you let us know what support ticket # it is and I can ask them to take another look?

**Comment by Seb-AS** [comment]
@derrick-branch Case #00057059

**Comment by Seb-AS** [comment]
@derrick-branch any news?

**Comment by Seb-AS** [comment]
@derrick-branch any news?

**Comment by nateheber** [comment]
I think Branch is in quarantine.

**Comment by derrick-branch** [comment]
@Seb-AS we are investigating internally. Support and engineering have reproduced and are digging in further.

**Comment by Seb-AS** [comment]
@derrick-branch @echo-branch any news?

**Comment by derrick-branch** [comment]
Engineering is continuing to investigate possible root causes. We haven't isolated the root cause yet

**Comment by derrick-branch** [comment]
@Seb-AS do you have Branch live in your app on the App Store? We've tried reproducing with your app but it seems you're not yet live with Branch. That would help with reproducing.

**Comment by Seb-AS** [comment]
@derrick-branch it's live at the time we sent the email, right now it's not using branch.
Maybe we can add someone to our testflight to use an older version with branch integration.

**Comment by Seb-AS** [comment]
@derrick-branch we're going to release a new version today using branch

**Comment by derrick-branch** [comment]
Thanks @Seb-AS. Once this happens, we can ask our engineer to attempt to reproduce again.

**Comment by sibljon** [comment]
We are experiencing a very similar issue. It's our production app, so can be tested quite easily. Email me at jon [ at ] sprucehealth.com for testing instructions. I'm going to email Branch support now with my findings.

**Comment by Seb-AS** [comment]
@derrick-branch appstore version ready https://apps.apple.com/us/app/marinemax/id1475146592

**Comment by derrick-branch** [comment]
Thanks @Seb-AS. Notified engineering that they can continue attempting to reproduce. 

@sibljon we may reach out to you if we're unable to test with @Seb-AS's app

**Comment by jleebranch** [comment]
@Seb-AS Are you guys still seeing this issue? I just tested deferred deep linking using getapp.marinemax.com/stpete. I clicked on IOS Chrome and I was deep linked as expected. 

If you're still seeing this issue, do you mind posting your user-agent from your IOS Chrome browser? (https://www.whatsmyua.info/) Thank.

**Comment by Seb-AS** [comment]
@jleebranch we're still seeing the issue.
if you use the link getapp.marinemax.com/stpete on safari, it'll open the app store to get the app, and then on open it will go to the home screen without adding your zipcode.
On IiOS Chrome, open the appStore but then it's not sending the info to the app to go directly to the home screen instead you're stuck on the zipcode screen.

user-agent :
According to useragent v2.2.1:

ua

rawUa: Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/80.0.3987.95 Mobile/15E148 Safari/604.1
string:
family: Chrome Mobile iOS
major: 80
minor: 0
patch: 3987
device: iPhone 0.0.0
os

string: iOS 13.3.0
family: iOS
major: 13
minor: 3
patch: 0

**Comment by jleebranch** [comment]
@Seb-AS Thanks for the info. Looking into it now.

**Comment by jleebranch** [comment]
@Seb-AS I created a test link with the same deep link data as getapp.marinemax.com/stpete:

https://getapp.marinemax.com/GviSUjRAo5

Can you go through the entire process of clicking through IOS Chrome and installing your App using this test link? I'm trying to isolate your click and install event.

Also, can you please email me the IDFA from your iPhone device? You can get the IDFA using our device id tool: https://apps.apple.com/us/app/branch-device-id-finder/id1477763736.

Please email to jlee@branch.io. Thanks.

**Comment by Seb-AS** [comment]
> @Seb-AS I created a test link with the same deep link data as getapp.marinemax.com/stpete:
> 
> https://getapp.marinemax.com/GviSUjRAo5
> 
> Can you go through the entire process of clicking through IOS Chrome and installing your App using this test link? I'm trying to isolate your click and install event.
> 
> Also, can you please email me the IDFA from your iPhone device? You can get the IDFA using our device id tool: https://apps.apple.com/us/app/branch-device-id-finder/id1477763736.
> 
> Please email to [jlee@branch.io](mailto:jlee@branch.io). Thanks.

On the latest version deeplinking with chrome seems to work as expected.

Thanks for your help
