### ISSUE TITLE
andoidx.localbroadcastmanager dependecy needed

### ISSUE THREAD

**Issue by jjd314** [BranchMetrics/react-native-branch-deep-linking-attribution#557]
When I added react-native-screens to a project that uses react-native-branch, the branch compile started failing with:

`Type androidx.localbroadcastmanager.content.LocalBroadcastManager was not found, it is required for default or static interface methods desugaring of void io.branch.rnbranch.RNBranchModule$1.generateLocalBroadcast(org.json.JSONObject, android.net.Uri, io.branch.indexing.BranchUniversalObject, io.branch.referral.util.LinkProperties, io.branch.referral.BranchError)`

I then created a clean project, installed react-native-branch alone, and added:

    implementation 'androidx.appcompat:appcompat:1.1.0'

to its dependencies, and got the same error.  I'm not an Android developer, so I have no idea what is going on, but by trial and error I found that if I add:

    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

to react-native-branch/android/build.gradle's dependencies, the problem goes away.  Since Branch does seem to explicitly depend on LocalBroadcastManager, perhaps there should be a dependency?

**Comment by jdee** [comment]
Thanks for reporting that, @jjd314. This apparently is the root of the issue: https://stackoverflow.com/a/58663263. This should only be a problem when using/updating to appcompat 1.1.0 (as opposed to 1.0.0). Among the examples in this repo, webview_example uses react-native-screens@1.x, and testbed_simple doesn't use react-native-screens at all. Both run. And the issue you reported occurs as an exception at runtime, not a compile time error. The import of LocalBroadcastManager does not fail at compile time in RNBranchModule.java. I have a feeling the localbroadcastmanager was pulled in by some element of the RN environment in past releases, possibly not appcompat.

We'll need to release a patch with the localbroadcastmanager dependency and look into using something other than LocalBroadcastManager (which was originally in the RN how-to-build-a-module docs).

**Comment by jdee** [comment]
See SDK-926 in internal Jira.
