### ISSUE TITLE
Didn't find class "io.branch.referral.BranchUtil$PluginType"

### ISSUE THREAD

**Issue by sudiddo** [BranchMetrics/react-native-branch-deep-linking-attribution#558]
I got this error, while trying to build the app. I'm using react-native branch 4.3.0, and i hope that the new version 4.4.0 can help me fix this. But there's no fix, is it related to referral change in google policy?

> java.lang.NoClassDefFoundError: Failed resolution of: Lio/branch/referral/BranchUtil$PluginType;

> at io.branch.rnbranch.RNBranchModule.getAutoInstance(RNBranchModule.java:98)

I also looking at the node_modules, RNBranchModule.java

is this the culprit?
<img width="508" alt="Screen Shot 2020-03-24 at 01 43 23" src="https://user-images.githubusercontent.com/12172974/77351853-ef7e0680-6d70-11ea-913b-e7d91b396d5f.png">

**Comment by blueberry6401** [comment]
Same here. I was able to run with branch 4.3 but now I can't run both on 4.3 and 4.4.

**Comment by jdee** [comment]
It looks like somehow you have a bad version of the Branch Android SDK. Not sure how that would happen. With react-native-branch@4.x, we pin to a specific version of the native SDK. In react-native-branch@4.4.0, it is Android 4.3.2: https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/android/build.gradle#L33.

In version 5.0.0 of the native Android SDK, the BranchUtil.PluginType enumeration was removed. I'm not sure how you would update the native SDK without manually modifying the build.gradle installed under node_modules (node_modules/react-native-branch/android/build.gradle should be the same as the master branch, that link above).

If you continue to have trouble, can you please contact support@branch.io to open a ticket and let us help evaluate and triage your issues? Thanks.

**Comment by sudiddo** [comment]
<img width="650" alt="Screen Shot 2020-03-25 at 16 39 50" src="https://user-images.githubusercontent.com/12172974/77522712-4130a900-6eb7-11ea-9c12-ce719e3e9cdd.png">

I already implement the newest android sdk for branch, it's still not working. What can i do?

**Comment by blueberry6401** [comment]
> It looks like somehow you have a bad version of the Branch Android SDK. Not sure how that would happen. With [react-native-branch@4.x](mailto:react-native-branch@4.x), we pin to a specific version of the native SDK. In react-native-branch@4.4.0, it is Android 4.3.2: https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/android/build.gradle#L33.
> 
> In version 5.0.0 of the native Android SDK, the BranchUtil.PluginType enumeration was removed. I'm not sure how you would update the native SDK without manually modifying the build.gradle installed under node_modules (node_modules/react-native-branch/android/build.gradle should be the same as the master branch, that link above).
> 
> If you continue to have trouble, can you please contact [support@branch.io](mailto:support@branch.io) to open a ticket and let us help evaluate and triage your issues? Thanks.

I've just found I have this line in app/build.gradle
`implementation 'io.branch.sdk.android:library:4.+'`
Remove this line and it will work.

**Comment by sudiddo** [comment]
It works, thank you @blueberry6401 !
