### ISSUE TITLE
getLatestReferringParams fails like 50% of the time 

### ISSUE THREAD

**Issue by lukebars** [BranchMetrics/react-native-branch-deep-linking-attribution#559]
We're having some issues when calling method getLatestReferringParams. 

Comparing the numbers we see on branch and we post to our servers we can see that it fails to deliver actual referring parameters at least 50% of the time on iOS devices, and most of the time for android device users on production app. 

Here's how we call your function: 

```javascript
branch.getLatestReferringParams(true).then(params => post(params)) 
```

Any ideas why this is happening?

**Comment by jdee** [comment]
Without knowing more about your use case, etc, I'm not sure. We have a section in the docs on misuses of getLatestReferringParams: https://help.branch.io/developers-hub/docs/react-native#section-using-get-latest-referring-params-to-handle-link-opens. You'll usually get the best results by just using the params in the subscribe callback whenever it's invoked, e.g.:

```js
branch.subscribe({ params, error } => {
  post(params);
});
```

Note also that the subscribe callback is invoked whenever a deferred deep link check is performed, often with an empty result. I believe this empty result will overwrite whatever is returned by getLatestReferringParams as well. This basically just returns the last thing that was passed to the callback.

I don't know if this will help address your issues. If you continue to have trouble, could you please contact support@branch.io to open a ticket, and we can sort everything out? Thanks!
