### ISSUE TITLE
Subscribe is run twice on android with error

### ISSUE THREAD

**Issue by sanjaypojo** [BranchMetrics/react-native-branch-deep-linking-attribution#569]
This seems to be a regression that's related to https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/79

We get the following error on android:
```
Warning. Session initialization already happened. To force a new session, set intent extra, "branch_force_new_session", to true.
```

We're wondering if this causes multiple callbacks to fire in some cases, because we've seen this happen where a navigation event is triggered multiple times by a branch deeplink.

We're using `"react-native-branch": "^5.0.0-beta.1"`

**Comment by jdee** [comment]
Are you calling `reInitSession` anywhere, e.g. in `Activity.onResume`? The solution may be just don't call `reInitSession`. I need to clean that up in the docs.

If you continue to have trouble, could you please contact support@branch.io to open a ticket? We can help you get sorted out there.

**Comment by sanjaypojo** [comment]
Yes we are calling it in `MainActivity.java`:
```
// Override onNewIntent for branch:
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
        RNBranchModule.reInitSession(this);
    }
```
So I can just remove this block completely?

**Comment by jdee** [comment]
No, just remove `reInitSession`. The other things are necessary.

**Comment by sanjaypojo** [comment]
Okay, replacing the above block with this then:
```java
// Override onNewIntent for branch:
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
```

**Comment by sanjaypojo** [comment]
Confirmed that it's now working, thanks @jdee :)

**Comment by jdee** [comment]
Docs have now been updated as well.

**Comment by StarryFire** [comment]
Hi, i am not calling `RNBranchModule.reInitSession(this);` in my code and yet this error is happening for me on Branch v5.0
This happens when i click on the app notification while the app is still in foreground

**Comment by m4r00p** [comment]
Any luck with this guys?
