### ISSUE TITLE
[ios]branch.subscribe called many times with deep link

### ISSUE THREAD

**Issue by quangdh** [BranchMetrics/react-native-branch-deep-linking-attribution#570]
I use branch.subcribe() to listen new deep link.
Example: myapp://purchase/SKU_Test
```
let _unsubscribeFromBranch = branch.subscribe(({error, params}) => {
      console.log("check deep link", error, params); // this line
      if (error) {
        console.error('Error from Branch: ' + error);
        return;
      }

      let url;
      if (params['+clicked_branch_link']) {
        url = params['~referring_link'];
      } else if (params['+non_branch_link']) {
        url = params['+non_branch_link'];
      }
      
      if (url && url.includes('myapp://')) {
         purchase()
      }
})
```

the subscribe callback is called many times. With the universal link, everything are ok. 
Please help me to check it!

**Comment by markmoomoo** [comment]
same thing, message broadcast at least twice cause a bug and have to debounce to prevent a function in it called twice

**Comment by Reenagrg100** [comment]
Same here.

**Comment by gdeluna-branch** [comment]
Closing out old issues, if this persists please open a ticket with support. https://help.branch.io/using-branch/page/submit-a-ticket
