### ISSUE TITLE
Device locale/language not being picked up on iOS

### ISSUE THREAD

**Issue by alexbrazier** [BranchMetrics/react-native-branch-deep-linking-attribution#571]
We are seeing an issue where the device locale is not being sent with branch.io events when using iOS. We are always seeing `EN` in the language field. The correct language is reported on Android.

### Steps to reproduce
- Setup branch.io on iOS for react native
- Set your device language to something like Spanish
- Send event, e.g custom event to branch.io
- Check branch.io liveview and see that the language is always `EN`

### Expected behaviour
- Should see event with language `ES` when using spanish

### Platform
iOS (iPhone 8 13.3.1)
(works as expected on Android)

### Version
`react-native-branch: 4.4.0`

**Comment by echo-branch** [comment]
The locale should be picked up automatically by the underlying native iOS SDK.  Is this behavior constant across devices?  

Going to file a ticket to look into this in the upcoming sprint.

**Comment by alexbrazier** [comment]
Thanks!
Yes we've been testing on multiple iOS devices and all the events are coming back with the `EN` locale. I put iPhone 8 just as I had personally verified the issue on it.

I've noticed you've got a v5 beta version out with a new iOS SDK version, but I haven't had a chance to update and test that for a fix.
