### ISSUE TITLE
Properties for branch_Share Started event are incorrect

### ISSUE THREAD

**Issue by LydGol90** [BranchMetrics/react-native-branch-deep-linking-attribution#574]
react-native: 0.62.2
react-native-branch: ^5.0.0-beta.1
platform: iOS (android unknown)

Hi, I am using branch and exporting events to segment exactly as described in these docs: https://help.branch.io/using-branch/docs/segment-export

I am seeing an issue where the properties sent with the `branch_Share Started` and `branch_Shared Completed` events are wrong. Instead of being the properties on the share object I have just created, the properties are those of the branch link from which I most recently opened the app.

Additionally if I have a totally new organic install of the app (so no branch link has been used to open it previously) then I do not see the `branch-Stare Started/Completed` events at all. 

To replicate:
- Set up react native app with react-native-branch and allow data export to Segment.
- After fresh organic install, create a branch share link using `createBranchUniversalObject` in your app with a set of properties (call these properties A).
- The shared link is correct but I never receive a `branch_Share Started` or `branch_Share Completed` event.
- Open your app from that branch link
- Create a branch share link again in your app with a set of properties (call these properties B).
- The link shared will have the correct properties (B) but if you look at the event in Segment the `branch_Share Started` and `branch_Share Completed` events have the wrong properties (A). 

I assume these two are related. I am not sure if this is an issue with this lib or the branch SDK or segment, but segment seems unlikely as I am seeing the same issue if I export to Amplitude instead of Segment.

Any help would be greatly appreciated, many thanks.

**Comment by gdeluna-branch** [comment]
Closing out old issues. This seems like an integration issue, please open a ticket with support. https://help.branch.io/using-branch/page/submit-a-ticket
