### ISSUE TITLE
Customize android ShareSheetStyle and sharing channel

### ISSUE THREAD

**Issue by alaminopu** [BranchMetrics/react-native-branch-deep-linking-attribution#577]
Is there any way to customize android share sheet style? Currently, it's bit cut off from both side. Would be nice to set it Full width.  According to branch [documentation](https://help.branch.io/using-branch/docs/content-sharing), it's possible to set it to full width. But I don't know how to do it in react-native. 

![Screenshot_20200610-163850](https://user-images.githubusercontent.com/1296554/84281726-37732500-ab39-11ea-9f8e-67c8adef7d22.png)

Also, is there any option to change the order of sharing channel?. I want to put "WhatsApp", "Instagram" on top of the list. 

if it's not possible to customize, is there any way to use default sharing option in android? 

![android_share_image](https://user-images.githubusercontent.com/1296554/84281897-67bac380-ab39-11ea-868a-d97dfe059eef.png)

**Comment by jamesholcomb** [comment]
You can do this with a combination of branchUniversalObject.generateShortUrl() to obtain a short link then [Share](https://reactnative.dev/docs/share.html) to get the built-in Android modal.

**Comment by bauerpm** [comment]
> You can do this with a combination of branchUniversalObject.generateShortUrl() to obtain a short link then [Share](https://reactnative.dev/docs/share.html) to get the built-in Android modal.

This worked for me.  Thanks!

**Comment by ZaikinaEvgeniya-2** [comment]
Are you find the way how change the order of sharing channel? Even if use `.addPreferredSharingOption(SharingHelper.SHARE_WITH.TWITTER)` right in java code, 
it is not use real order, it just add app in the first screen but in own order

**Comment by utkuertas** [comment]
> You can do this with a combination of branchUniversalObject.generateShortUrl() to obtain a short link then [Share](https://reactnative.dev/docs/share.html) to get the built-in Android modal.

can you explain more pls?

**Comment by gdeluna-branch** [comment]
> You can do this with a combination of branchUniversalObject.generateShortUrl() to obtain a short link then [Share](https://reactnative.dev/docs/share.html) to get the built-in Android modal.

I recommend following this approach while we determine any future UI/UX work.
