### ISSUE TITLE
Not opening the app on iOS

### ISSUE THREAD

**Issue by khanhduy62** [BranchMetrics/react-native-branch-deep-linking-attribution#579]
Hello everyone,
I implemented this module. When I click the link, it takes me to the custom URL that I have given in the branch dashboard and not to the app (app is already there).
Can anyone tell me why I'm wrong. Please help me, thank you.
1.
<img width="698" alt="Screen Shot 2020-06-19 at 5 49 24 PM" src="https://user-images.githubusercontent.com/16585137/85125496-f1634300-b255-11ea-8556-9c05f7e9f242.png">
2.
<img width="710" alt="Screen Shot 2020-06-19 at 5 56 56 PM" src="https://user-images.githubusercontent.com/16585137/85125689-4b640880-b256-11ea-8b06-154f199a83a0.png">
3.
<img width="1153" alt="Screen Shot 2020-06-19 at 5 49 41 PM" src="https://user-images.githubusercontent.com/16585137/85125536-0049f580-b256-11ea-8666-5330d33192bd.png">

**Comment by cenaHara** [comment]
same issue , hi @khanhduy62 any solution ?

**Comment by khanhduy62** [comment]
@cenaHara It's my misunderstanding, it could be run if you use iphone camera to scan
