### ISSUE TITLE
null is not an object (evaluating 'RNBranch.STANDARD_EVENT_ADD_TO_CART')

### ISSUE THREAD

**Issue by MrAlekhin** [BranchMetrics/react-native-branch-deep-linking-attribution#580]
For some reason `RNBranch` is null 🤷‍♂️
- React Native: 0.59.9
- react-native-branch: 3.0.0 (tried also ^3.0.0)
- using pod 'react-native-branch', path: '../node_modules/react-native-branch' 
- also, in AppDelegate.m we are not able to use <react-native-branch/RNBranch.h>. We have to use <RNBranch.h> instead. 

![Screen Shot 2020-06-20 at 1 01 20 AM](https://user-images.githubusercontent.com/24749983/85192722-951e1480-b291-11ea-9ea7-e2bc4837dd62.png)

**Comment by kraegpoeth** [comment]
+1

**Comment by Mactub07** [comment]
duplicate #568

**Comment by codal-mpawar** [comment]
@kraegpoeth @Mactub07 @MrAlekhin @dmitrig01 @samtingleff Any update regarding this issue.
I am facing an issue in expo can someone help me to find out the root cause.

**Comment by Ryanjso** [comment]
> @kraegpoeth @Mactub07 @MrAlekhin @dmitrig01 @samtingleff Any update regarding this issue. I am facing an issue in expo can someone help me to find out the root cause.

+1

**Comment by gdeluna-branch** [comment]
Closing out old issues. If this repros on the latest please make a new issue.
