### ISSUE TITLE
branch.getFirstReferringParams() returning blank always

### ISSUE THREAD

**Issue by vikasrai1502** [BranchMetrics/react-native-branch-deep-linking-attribution#581]
Getting blank values everytime.

**Comment by Sytree** [comment]
got same issue in version 5.0.0

**Comment by sangupandi** [comment]
Any updates regarding this

**Comment by gdeluna-branch** [comment]
First referring params will always return the same value per app installation. If the link used to install app had no params, it will always be blank.

For further help please open a ticket with support https://help.branch.io/using-branch/page/submit-a-ticket
