### ISSUE TITLE
Branch link in an Intercom message opens browser first instead of the app

### ISSUE THREAD

**Issue by YeshanJay-Urban** [BranchMetrics/react-native-branch-deep-linking-attribution#584]
I'm finding it hard to get Branch.io deeplinking to work with Intercom.

The Branch link works well when opened via native Messages app - opens the app directly when tapped.

But if we send this link through an Intercom message, and then tap on it on the phone, the result is not as expected:

----------

## On iOS ##

- Open Intercom messages view.
- Tap on the Branch link (sent from Intercom console).
- Browser opens with an alert asking to open the native app ('Open this page in "MyApp"?').
- Press "Open".
- App detects the Branch parameters on the link and redirects to the correct page.

<br />

***Expected Behavior***

App should detect the link directly without being handed over by browser. 

<br />

----------

## On Android ##

- Open Intercom messages view.
- Tap on the Branch link (sent from Intercom console).
- List of suggested apps pops up - including "MyApp".
- Tap on "MyApp".
- App detects the Branch link ONLY, but without the parameters - which then will not redirect to any page.
  - Now send the app to the background (eg: Tap on home button), and then open "MyApp" again.
  - Branch will now detect the link with the parameters and redirect to the correct page *(this sometimes happens in iOS as well)*.

<br />

***Expected Behavior***

Branch should detect the link **with parameters** directly, without the need to send the app to background and reopen. 

<br />

----------

Does anyone have an idea what I have missed out on? or a workaround?

I was thinking to setup Universal Links by uploading the Association File.. 🤷‍♂️

Btw, Branch.io configurations are all done and works perfectly with other social media apps.

<br />

```
react-native: 0.61.5
react-native-branch: 5.0.0-beta.1
react-native-intercom: 16.0.0
```

**Comment by shivam-urbanyogi** [comment]
Hey, facing the same issue on iOS, have you solved this issue?

**Comment by jay-s-kipl** [comment]
Hello,
This same issue we are facing in our Application for both iOS and Android platform.

Have you any update for solving this issue?
Please let me know.

**Comment by gdeluna-branch** [comment]
For integration help please open a support ticket https://help.branch.io/using-branch/page/submit-a-ticket
