### ISSUE TITLE
branch unsubscribe isnt working 

### ISSUE THREAD

**Issue by pabloearg** [BranchMetrics/react-native-branch-deep-linking-attribution#590]
I'm using this configuration :

```
react-native: 0.61.5
react-native-branch: 4.3.0"
```
and using this code to subscribe to a branch callback, 

```
this._unsubscribeFromBranch = branch.subscribe(async ({ error, params }) => {
            this._unsubscribeFromBranch();
            this._unsubscribeFromBranch = null;
            this.branchCallback(error, params, sessionToken);
          });
```

and in the same component:

```
componentWillUnmount() {
    if (this._unsubscribeFromBranch) {
      this._unsubscribeFromBranch();
      this._unsubscribeFromBranch = null;
    }
  }
```
with this configuration the callback is been trigger, but when in android the back key is pressed and the app is sent to background (app closes, but isn't killed) after re enter the app, the callback is been trigger on app start, even if this line is executed:

`this._unsubscribeFromBranch();
`

is there a better way to unsubscribe all events after a branch.subscribe?

**Comment by leoz2007** [comment]
Any news about this issue?

**Comment by lebars-r** [comment]
I have a similar issue  as well. In my workflow there is places where I need to unsubscribe and re-subscribe but it bring me back to the first subscription instead of the new one (even though It should have been unsubscribed)

**Comment by spacesuitdiver** [comment]
Using react-native-branch 5.0.1 this is still a problem. Thoughts on a solution?

**Comment by Solid-Metal** [comment]
yep, still problem with me using 5.0.1 as well

**Comment by gdeluna-branch** [comment]
Should be resolved. Please open a new ticket if this persists in the latest version.

**Comment by Tarun24RN** [comment]
Yes issue still persists i am using version 5.6.2
