### ISSUE TITLE
RCTLinkingManager vs RNBranch in AppDelegate.m

### ISSUE THREAD

**Issue by sergiulucaci** [BranchMetrics/react-native-branch-deep-linking-attribution#591]
Hei BranchIO team. 

This is more like a doc-confusion which might be useful for others, that's why I am opening an issue.

I have RCTLinkingManager set up in AppDelegate.m for both deep and universal links. 

**Question 1** 
If I want to use only RNBranch manager I assume I would remove RCTLinkingManager at all from this file, right? 

**Question 2**
But what if I were to use both RCTLinkingManager and RNBranch instead? 

This is how it looks before BranchIO:

```
// Respond to URI scheme links
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Respond to Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
```

Should it look like this?

```
// Respond to URI scheme links
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RNBranch application:app openURL:url options:options] ||
    [RCTLinkingManager application:application openURL:url options:options];
}

// Respond to Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  return [RNBranch continueUserActivity:userActivity] ||
    [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
```

Thank you!

**Comment by amehrainnow8** [comment]
Thanks man, for asking. I was having the same doubt

**Comment by ryanbabbly** [comment]
Would also like to know this as ios won't build for me while both exist together and I don't see mention of this anywhere in the docs

**Comment by dibakar95** [comment]
This solves the issue. https://stackoverflow.com/questions/38945790/appdelegate-m-for-both-fbsdk-and-linkingmanager/38945881

**Comment by SeanDunford** [comment]
Pasting this here so people don't have to click through to StackOverflow. 

`[RNBranch application:application openURL:url options:options];` returns a BOOL, if that is true then Branch handled the link and you should exit out of the function returning `True/Yes` if not, pass the app/options to your other link handlers. 

Should look something like this: 
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  // Required for opening links from JS
  BOOL branchOpened = [RNBranch application:application openURL:url options:options];
  if (branchOpened){
    return YES;
  }
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

**Comment by iledzka** [comment]
> // do other deep link routing for the Facebook SDK, Pinterest SDK,

For anyone that was confused by this line:
`if ([RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    }`
There used to be [an error in the Branch documentation](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/606) .

So it should be 
`if ([RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    }`
or simply follow @SeanDunford 's solution.
