### ISSUE TITLE
"Unsupported Type" for object types when deep link generated via generateShortUrl

### ISSUE THREAD

**Issue by mkuligowski** [BranchMetrics/react-native-branch-deep-linking-attribution#592]
Hello,

I am generating deep links via both: REST API and react-native library, however there is a small difference, when passing custom objets. For example, when deep link is generated via REST api:

```
{
  "branch_key": "key_test_xxxx",
  "channel": "RNApp",
  "feature": "share",
  "data": {
    "$canonical_identifier": "Item",
    "$og_title": "Title",
    "$og_description": "Description!",
    "$desktop_url": "https://desktop.url",
    "custom_object": { "itemId": 142 }
  }
}
```

Once clicked on mobile device, `custom_object` object exists in `branch.subscribe` params.

However, while generating deep link via react-native library, when doing the same, `custom-object` has `Unsupported Type` value (where I am expecting `{ "itemId": 142 }` ). 

The following code snippet shows how deep link is generated on frontend:

```
    let branchUniversalObject = await branch.createBranchUniversalObject('Item', {
      title: 'Title,
      contentDescription: 'Description',
    });

    let linkProperties = {
      feature: 'share',
      channel: 'RNApp'
    }

    let controlParams = {
      $desktop_url: 'https://desktop.url',
      custom_object: {
        itemId: 142
      }
    }

    let {url} = await branchUniversalObject.generateShortUrl(linkProperties, controlParams);
```
So here are my questions:
1. Is it possible to generate deep link with custom object via react-native library?
2. If yes - how to achieve it?

**Comment by gdeluna-branch** [comment]
For integration help please open a support ticket https://help.branch.io/using-branch/page/submit-a-ticket
