### ISSUE TITLE
Incorrect integration documentation

### ISSUE THREAD

**Issue by SRandazzo** [BranchMetrics/react-native-branch-deep-linking-attribution#606]
Hi,

The documentation listed here https://help.branch.io/developers-hub/docs/react-native#swift is incorrect. Select the Objective-C tab and it reads as follows:
![image](https://user-images.githubusercontent.com/307819/95100509-2b6e2d00-06ff-11eb-99a3-a68f330892fe.png)

Highlighted portion should actually read (adding a `!`)
```Objective-C
 if (![RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
  }
```

The example in the repo is correct and includes the `!`:
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/a69c730ba8bdce592b222e058555c493898cba48/examples/testbed_native_ios/ios/testbed_native_ios/AppDelegate.m#L30

Thanks

**Comment by jkadamczyk** [comment]
Hey! I actually agree with this issue. I was bamboozled when I was reading this.
