### ISSUE TITLE
iOS showShareSheet on Cancelled or Dismiss dialog promise doesn’t resolve

### ISSUE THREAD

**Issue by muhammadimran26** [BranchMetrics/react-native-branch-deep-linking-attribution#607]
Hey, usually for showShareSheet if theres an error or when its completed the function would return `{Channel , Completed and Error }` . However, it seems that the promise doesn’t resolve/reject in case of modal dismiss by pressing background which results.

Thanks

**Comment by Aryk** [comment]
I think I might be experiencing this as well...have you been able to figure it out?

**Comment by Aryk** [comment]
I had to basically remove "await", but now I don't know when the sheet is closing.
