### ISSUE TITLE
Remove deprecated unarchiveObjectWithData methods

### ISSUE THREAD

**Issue by kyleclegg** [BranchMetrics/react-native-branch-deep-linking-attribution#618]
The method `unarchiveObjectWithData` is deprecated and deemed unsecure/less secure than unarchive*OfClass. Please remove the following instances of use:

- BNCKeyChain.m
- BNCPreferenceHelper.m
- BNCServerRequestQueue.m

**Comment by echo-branch** [comment]
Going to move this to an iOS SDK issue.  Needs to be done.

**Comment by echo-branch** [comment]
This is going to slip a bit.  Since our min supported version is lower than iOS 11, we have to maintain both methods of handling this. We're looking at whether raising the min version makes more sense than maintaining both versions.

**Comment by kyleclegg** [comment]
@echo-branch understandable. Thanks for staying on top of it. It's not a huge rush but our organization would welcome the improved security.

**Comment by gdeluna-branch** [comment]
Resolved.
