### ISSUE TITLE
IDFV is not correct

### ISSUE THREAD

**Issue by taschik** [BranchMetrics/react-native-branch-deep-linking-attribution#624]
It seems to me that Branch's react-native SDK is retrieving/generating an IDFV that is not the same as e.g. `react-native-device-info` or `amplitude-js` generate. RN-device-info and Amplitude are the same but Branch.io's IDFV is different.

This leads to the issue that data cannot be attributed and matched when integrating with e.g. Amplitude.

**Comment by echo-branch** [comment]
@taschik 
Let's confirm what Apple is giving us via direct calls and compare to what being returned by the libraries.

Log the current identifiers from native iOS code.  This can be done from almost anywhere in native code, the AppDelegate didFinishLaunching is a good spot.

ObjC Example.  This requires AdSupport.framework for the IDFA, which is not included by default by Branch.
`
- (void)printAppleIdentifiers {
    NSLog(@"IDFV: %@", [[UIDevice currentDevice].identifierForVendor UUIDString]);
    NSLog(@"IDFA: %@", [ASIdentifierManager sharedManager].advertisingIdentifier);
}
`

On a device without the app installed and tracking allowed, install and check if the values printed here match what the libraries provide.

For Branch, we default to returning IDFA and IDFV.  If IDFA is not allowed, we return IDFV in both locations. Finally, if none are allowed we return a randomly generated guid, for example when running an App Clip.

Looking at the docs for those other libraries, it seems they do not default to IDFA by default.  Which could explain the difference.

**Comment by gdeluna-branch** [comment]
Closing out due to lack of activity.
