### ISSUE TITLE
Branch.IO and Clevertap Integration issue ($clevertap_attribution_id is not getting sent to Branch)

### ISSUE THREAD

**Issue by Cshayan** [BranchMetrics/react-native-branch-deep-linking-attribution#631]
Hey, I am integrating Branch.IO and Clevertap in react-native app following these docs: 

[https://help.branch.io/using-branch/page/clevertap](url) 
[https://developer.clevertap.com/docs/branch](url)

In the docs, for Android it is mentioned to call the `setRequestMetadata()` of Branch to pass the `$clevertap_attribution_id` before Branch's initSession is being called.

However, I can see in many cases the attribution id is not getting passed to Branch metadata while Branch SDK is calling their Install API. See the below log ->

```
Posting to https://api2.branch.io/v1/install
2021-03-04 12:47:01.788 26322-26440/someapp.in.random.app I/BranchSDK: Post value = {"hardware_id":"394526592407b3a6","is_hardware_id_real":true,"brand":"Google","model":"Android SDK built for x86","screen_dpi":420,"screen_height":1794,"screen_width":1080,"wifi":false,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android","os_version":29,"cpu_type":"i686","build":"sdk_gphone_x86-userdebug 10 QSR1.200715.002 6695061 dev-keys","locale":"en_US","connection_type":"mobile","device_carrier":"Android","os_version_android":"10","country":"US","language":"en","local_ip":"10.0.2.15","app_version":"1.93","facebook_app_link_checked":false,"is_referrable":0,"debug":false,"update":0,"latest_install_time":1614842064980,"latest_update_time":1614842064980,"first_install_time":1614842064980,"previous_update_time":0,"environment":"FULL_APP","metadata":{},"advertising_ids":{"aaid":"c8083e6f-8b8e-4431-a38d-2925e918b2a9"},"lat_val":0,"google_advertising_id":"c8083e6f-8b8e-4431-a38d-2925e918b2a9","instrumentation":{"v1\/install-qwt":"0"},"sdk":"android5.0.3","branch_key":"<branch_live_key>"}
```
Hence while Branch is calling the Clevertap's webhook, Clevertap is returning 400 response.

![Screenshot (35)_LI](https://user-images.githubusercontent.com/45463444/110664102-2309a900-81ed-11eb-9b36-29d6eaa2037f.jpg)

Below is an overview of my approach ->

`MainActivity.java`

```
import com.clevertap.android.sdk.CleverTapAPI;
import io.branch.rnbranch.RNBranchModule;

public class MainActivity extends ReactActivity {
    CleverTapAPI cleverTapAPI;

    .....
    
    @Override
    protected void onStart() {
       super.onStart();
       Branch.enableLogging();
       cleverTapAPI = CleverTapAPI.getDefaultInstance(getApplicationContext());
       if (cleverTapAPI != null) {
           String clevertapId = cleverTapAPI.getCleverTapAttributionIdentifier();
           RNBranchModule.setRequestMetadata("$clevertap_attribution_id", clevertapId);
       } else {
           Log.e("clevertap branch integration","CleverTap is NULL during branch init session");
       }
       RNBranchModule.initSession(getIntent().getData(), this);
    }
    
     @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        RNBranchModule.onNewIntent(intent);
    }
}
```

`MainApplication.java`

```
import io.branch.rnbranch.RNBranchModule;

public class MainApplication extends Application implements ReactApplication {
 
     @Override
      public void onCreate() {
          super.onCreate();
         RNBranchModule.getAutoInstance(this);
      }
}           
```

Additional info:

Branch Android SDK version: 5.0.4
Clevertap Android SDK version: 3.9.0

**Note:** This issue is happening for most users, but sometimes the attribution_id is getting passed to Branch and in that case I am seeing 200 response when Branch calls Clevertap's webhook.

Any help/suggestion on how to proceed for this will be appreciated. Thank you!

**Comment by Cshayan** [comment]
@echo-branch Any update on the issue?

**Comment by mukesh-14** [comment]
@sriganesh-nagaraj were you able to simulate this?
We too are facing quite a few issues while integration

**Comment by sriganesh-nagaraj** [comment]
@mukesh-14 We created a custom event in branch and fired it on click of a branch link. This would appear in the webhooks dashboard. Branch would make request to clevertap but clevertap returned 400s as it requires a talk with their support to enable tracking of custom events from branch. So during development this was our only option to verify.

**Comment by mukesh-14** [comment]
oh okay.
For me the main use case is attribution. For some reason Branch isn't sending the UTM parameters to Clevertap.
How do we go about debugging this? any idea? I have integrated as the Branch docs

**Comment by sriganesh-nagaraj** [comment]
@mukesh-14  How are you testing it?

**Comment by mukesh-14** [comment]
I have created a quick link to test. I have my app installed. So I am just clicking the link which opens the app as expected. I am getting all the click events in Branch although the UTM parameters are not visible in Clevertap

**Comment by sriganesh-nagaraj** [comment]
Branch won't send click events to clevertap.

[INSERT DATA PARTNER NAME] supports the following events:

Installs
Lifecycle Events
Commerce Events
Content Events
Custom Events

The above is mentioned in https://help.branch.io/using-branch/page/clevertap

**Comment by sriganesh-nagaraj** [comment]
@mukesh-14 Since we can't test install events from branch links without releasing to stores, we tested the integration by firing custom events.

**Comment by mukesh-14** [comment]
So the link you sent, I am referring to the same documentation.
In the 5th step they have mentioned to check Branch Data
Check the "UTM Visited" event.
That is what I am doing.
So you are saying this "UTM Visited" event won't show data?

**Comment by sriganesh-nagaraj** [comment]
Nope, from what we tested we could see that event only after releasing the app to stores. Check my previous comment

**Comment by mukesh-14** [comment]
Yes understood. Only going live is the option then.
Thanks for help man! Really appreciate

**Comment by Md-Mudassir47** [comment]
@Cshayan were you able to link clevertap with branch io successfully? as per the new SDK the snippet is changed and I'm not sure where and how to import it and add it.
```
cleverTapInstance.getCleverTapID(new OnInitCleverTapIDListener() {
   @Override
   public void onInitCleverTapID(final String cleverTapID) {
   // Callback on main thread
   Branch branch = Branch.getInstance();
   branch.setRequestMetadata("$clevertap_attribution_id",
   cleverTapID);
   ...
   Branch.initSession(...);
   }  
});
```
ref: [integrate-branch](https://developer.clevertap.com/docs/branch#section-step-2-integrate-branch)

**Comment by Cshayan** [comment]
@Md-Mudassir47 I am not aware of this new approach, but for me I was able to solve it by creating a new custom id and passing to Clevertap. You can check this below link.

https://developer.clevertap.com/docs/set-clevertap-id

I am also passing the same id to Branch using `setRequestMetadata()` method.

**Comment by Cshayan** [comment]
@shubhamS-vs 

1. Please make sure you have enabled this below flag in your manifest file. This required if you are generating custom clevertap id.

`<meta-data
            android:name="CLEVERTAP_USE_CUSTOM_ID"
            android:value="1" />`

2. Also, check that for android the clevertap id generated must have __h in the prefix. So you need to append "__h" in the beginning with the clvertap id that is generated and then pass the final string generated (with __h) to Branch using setRequestMetadata(). Something like this - 

![carbon](https://user-images.githubusercontent.com/45463444/162379527-6fc7539d-1d66-4235-a7fe-21253a73aa7d.png)

Do all this logic inside the onStart() lifecycle method in MainActivity file.
