### ISSUE TITLE
Deep links do not bring user to the correct screen if the app is not open in the background.

### ISSUE THREAD

**Issue by kangpeter5** [BranchMetrics/react-native-branch-deep-linking-attribution#632]
Deep links take users to the correct page with the filters in place while the app is open in the background. However, if the app is not open, they only bring you to the Home Screen. 

Current setup
```
branch.subscribe(({ error, params, uri }) => {
	if (error) {
		console.error('Error from Branch: ' + error)
		return
	}
	if (params['+non_branch_link'] || !params['+clicked_branch_link']) {
		return
	}
	if (params['filter_types']) {
			      const filters = params['filter_types'].split(',').map((i) => i.trim())
			      const container = NavigatorService.getContainer()

			      container._navigation?.navigate(Routes.LocationsScreen, { filter: filters })
	}
})
```

**Comment by Vasault** [comment]
I've been dealing with several issues with branch.io and this is one of them

**Comment by sadia-onyxtec** [comment]
Did you solve it?

**Comment by gdeluna-branch** [comment]
Closing out old issues. This is an integration issue, please make a ticket with support https://help.branch.io/using-branch/page/submit-a-ticket
