### ISSUE TITLE
After opening app via custom deeplink it's being passed to onOpenComplete callback everytime when app goes foreground

### ISSUE THREAD

**Issue by mkraina** [BranchMetrics/react-native-branch-deep-linking-attribution#633]
Hello, I've added custom deeplink using 
```
<intent-filter android:autoVerify="true">
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="myscheme" />
</intent-filter>
```
When opening app via `myscheme://` it works as expected, the problem is I receive the `+non_branch_link` = `myscheme://` every single time I switch background>foreground afterwards
I believe the proble is indeed branch related as I tested out `Linking.addEventListener('url', callback);` which works just fine and responds only when the deeplink is really used
#### environment
```
react-native: 0.63.4,
react-native-branch: 5.0.1,
platform: android
```

**Comment by nateshmbhat** [comment]
facing same issue

**Comment by echo-branch** [comment]
@nateshmbhat 
This is likely an integration issue and this particular ticket is rather old. Could you file an issue with the support team. https://help.branch.io/using-branch/page/submit-a-ticket

We were without a dedicated React Native developer for some time and are still in the process of getting caught up on Github reported issues. Thanks.
