### ISSUE TITLE
ReferenceError: Can't find variable: proto when used with metro inlineRequires: true

### ISSUE THREAD

**Issue by adrienharnay** [BranchMetrics/react-native-branch-deep-linking-attribution#635]
Hello,

I am trying to enable `inlineRequires: true` in the metro config of the project I am working on, but when doing so I have the following error:

```
 INFO  Initializing react-native-branch v. 5.0.1
 ERROR  ReferenceError: Can't find variable: proto
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

I have tried importing `react-native-branch` at the root of my app, but that doesn't work.

Would you have any idea how to make this library work with inline requires?

Thanks in advance!

(I'm using react-native-branch 5.0.1 and react-native 0.64)

**Comment by JSuzara** [comment]
Hello, @adrienharnay. Have you found a solution? I'm currently facing the same problem and wanted to know if you've resolved this issue. Thanks

**Comment by adrienharnay** [comment]
Hello, I did not dig deeper sorry.

**Comment by mtoninelli** [comment]
Same issue here, any luck?

**Comment by gdeluna-branch** [comment]
Hi @mtoninelli, can you create a new issue with the version of react-native-branch and react-native you are using? As well as your environment such as android version.
