### ISSUE TITLE
Request to branch service timed out

### ISSUE THREAD

**Issue by atrofimenko** [BranchMetrics/react-native-branch-deep-linking-attribution#636]
Hello! Faced with a very rare issue, that is hard to reproduce. When we are trying to subscribe to brunch on start we are getting error(screenshot is applied). We have no possibility to reschedule this subscription after this error, have now idea how to avoid this problem, m.b. you can help us to solve this issue?
![Снимок экрана 2021-03-23 в 15 41 55](https://user-images.githubusercontent.com/62396722/112180201-652ee380-8c0c-11eb-8d48-72045510ef01.png)

**Comment by gdeluna-branch** [comment]
Closing old issues. Please open a new issue if this persists.
