### ISSUE TITLE
fatal error: module 'AdServices' not found

### ISSUE THREAD

**Issue by mnifakram** [BranchMetrics/react-native-branch-deep-linking-attribution#654]
I'm getting a build error when trying to archive the project for production build.
```
CompileC /Users/runner/Library/Developer/Xcode/DerivedData/Test-gtmzfwwipkwxacbbgxwyifnooroe/Build/Intermediates.noindex/ArchiveIntermediates/Test/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Branch.build/Objects-normal/arm64/BNCSystemObserver.o /Users/runner/work/1/s/ios/Pods/Branch/Branch-SDK/BNCSystemObserver.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Branch' from project 'Pods')
    cd /Users/runner/work/1/s/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target arm64-apple-ios9.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=/Users/runner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/runner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-metho...
/Users/runner/work/1/s/ios/Pods/Branch/Branch-SDK/BNCSystemObserver.m:24:9: fatal error: module 'AdServices' not found
@import AdServices;
 ~~~~~~~^~~~~~~~~~
1 error generated.
```

I added the AdServices framework but still same error every time 
![image](https://user-images.githubusercontent.com/2995199/120712976-3ad58e00-c4b9-11eb-9293-d9649514c3f3.png)

Any Ideas?
Thanks

**Comment by echo-branch** [comment]
The most common reason for this error is that you're on an old version of Xcode.  AdServices.framework is available with with Xcode 12.3+

**Comment by mnifakram** [comment]
yep that fixed my issue.

**Comment by atha-github** [comment]
I am using Xcode V12.0.1 how can I resolve the issue "AdServices.framework not found" without update xcode? My OS only can support upto Xcode V12.0.1.

**Comment by echo-branch** [comment]
@atha-github 
Although not recommended, you may comment out the code that references AdServices in the iOS code base. You will need to redo this change every time the Branch SDK is downloaded from cocoapods.

Open the iOS workspace in Xcode 
Find the Pods -> Branch -> BNCSystemObserver.m

Comment out the following code.
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BNCSystemObserver.m#L22-L28

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BNCSystemObserver.m#L66-L85
