### ISSUE TITLE
SDK stops functioning completely on Android until next app launch if there is an error

### ISSUE THREAD

**Issue by evelant** [BranchMetrics/react-native-branch-deep-linking-attribution#659]
Related to https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/658

The SDK stops functioning completely on Android until the next time the app is foregrounded if there is an error in `branch.subscribe`. For example:

1. Start app with internet connection disabled
2. `branch.subscribe` returns error `poor network connectivity. please try again later`
3. Re-enable internet connection -- nothing happens, callback is not called again now that we're online
3. call the unsubscribe function
4. call `branch.subscribe` again -- nothing happens, callback is never called
5. call `getLatestReferringParams` or `getFirstReferringParams` -- both return an empty object instead of throwing an error
6. There is now no way to "try again later", the SDK is non functional even though we're online!
7. Background the app and foreground it again by pressing app switcher key
8. subscribe callback fires _twice_ (unsubscribe didn't work, memory leak) with success

This behavior means that if an error happens in `branch.subscribe` that the branch SDK is effectively dead for the rest of the user's session. There is no way to handle an error or retry any operation, no way to prompt to the user to go online to try again.

**Comment by AndrewMorsillo** [comment]
Hmm it looks like the branch sdk is using the deprecated DeviceEventEmitter API -- deprecated 5 years ago! Perhaps that's part of the issue with unsubscribe not working.

https://stackoverflow.com/questions/58285364/react-native-deviceeventemitter-unsubscribe-from-event

**Comment by gdeluna-branch** [comment]
Resolved
