### ISSUE TITLE
Ios configuration with react-native-linking is duplicated with react-native-branch's 

### ISSUE THREAD

**Issue by byyoungjin** [BranchMetrics/react-native-branch-deep-linking-attribution#664]
I'm trying to integrate react navigation with this react-native-branch 
In react-navigation docs,  [they say it can be used with branch like this](https://reactnavigation.org/docs/deep-linking/#third-party-integrations) 

But I found both of libraries need to configure same function on AppDelegete.m 

1 . for react-native-linking
```
// Linking API (react-native-linking)
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links(react-native-linking)
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

2. for react-native-branch 
```
// Branch.io
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    if ([RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    }
    return YES;
}

// Universal Links(Branch.io)
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RNBranch continueUserActivity:userActivity];
}
```

so I needed to chose what to use. 
1. if I chose 1. react-native-linking configuration , 
I can use linking configuration which react-navigion5 provide. 
and 
- branch.getFirstReferringsParms()  
work. 

-branch.subscribe(({params}) =>{...}) 
seems to work, but the params it giving me is always 
{“+clicked_branch_link”: false, “+is_first_session”: false}  or 
 {“+clicked_branch_link”: false, “+is_first_session”: false, “+rn_cached_initial_event”: true} 

no other custom params, 

-branch.getLastesReferringsParams() 
also return same with subscribe. no custom params. 

2. so I replaced AppDelegate.m with 2. react-native-branch configuration 
in this way, linking configuration has no effect. Not triggered 

but -branch.getLastesReferringsParams()  give me the exact params that i sended with. 
branch.subscribe() also work. 

So I'm planning to chose react-native-branch configuration .. 

but this means the way [doc](https://reactnavigation.org/docs/deep-linking/#third-party-integrations) say is not correct. 

Is there any way that i can use react-navigation5 's linking configuration 
while getting correct latestParams ??

**Comment by byyoungjin** [comment]
I just found branch configuration changed  like this!! 
``` 
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    if ([RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    }
    return YES;
}
```

**Comment by derekblank** [comment]
@byyoungjin I had the same problem. I am using the Branch method you described in your second option, but check the [CHANGELOG](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/afbd90f51626e3465f787063d1305e075c618942/ChangeLog.md#updating-from-an-earlier-version) as the functions have now changed if you are using the latest Branch version @ 5.0.3. (Unfortunately this change is not in the documentation.):

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(nonnull NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RNBranch application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> *restorableObjects))restorationHandler {
  return [RNBranch continueUserActivity:userActivity];
}
```

Then if your link is something like `https://foo.test-app.link/123456789`, you can get the params from `branch.subscribe` and pass the `navigate` event from react-navigation,  and then do something like this:

```
const url = params.$deeplink_path;
const path = url.split('/');
const screen = path[0];

navigate(screen);
```

It's very basic, but it works, unless the URL comes from a Push Notification, in which case nothing happens -- I have no idea why, but am trying to figure that out.

Also I am exporting my `branchUnsubscribe` function from a separate file, and am importing it into a useLayoutEffect hook with `navigate` like this:

```
  useLayoutEffect(() => {
    if (navigate) {
      const branchUnsubscribe = branchSubscribe(navigate);

      return () => {
        branchUnsubscribe();
      };
    }
  }, [navigate]);
```

Hope this helps, let me know if you find out anything.

**Comment by hatn98** [comment]
same issue :(

**Comment by thanhtungkhtn** [comment]
still an issue

**Comment by cbarceloc** [comment]
same issue :(

**Comment by Vasault** [comment]
> Hi Everyone! I'fe found the solution!! Both configurations are compatible (deep linking and branch), but it is not documented anywhere. In order to make the config screens work in react navigation and branch, add or modify these two methods in the AppDelegate.m:
> 
> ```
> #import <RNBranch/RNBranch.h>
> #import <React/RCTLinkingManager.h>
> 
> 
> - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
> 
>   if ([RNBranch application:app openURL:url options:options])  {
>        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
>     [[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options];
>    }
>   
>   
>   return [RCTLinkingManager application:app openURL:url options:options];
> }
> 
> - (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
>   return [RNBranch continueUserActivity:userActivity] || [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
> }
> ```
> 
> and the navigator should look like this:
> 
> ```
> <NavigationContainer
>           ref={navigationRef}
>           linking={{
>             prefixes: ["https://yourapp.com", "yourapp://"],
>             config: {
>               screens: {
>                 [EVENT]: {
>                   path: "events/:eventId",
>                   parse: {
>                     eventId: decodeEventId
>                   }
>                 }
>               }
>             },
>             // Custom function to subscribe to incoming links
>             subscribe(listener) {
>               // First, you may want to do the default deep link handling
>               const onReceiveURL = ({ url }) => listener(url);
> 
>               // Listen to incoming links from deep linking
>               Linking.addEventListener("url", onReceiveURL);
> 
>               // Next, you would need to subscribe to incoming links from your third-party integration
>               // For example, to get to subscribe to incoming links from branch.io:
>               branch.subscribe(({ error, params, uri }) => {
>                 if (error) {
>                   handleError(`Error from Branch: ${error}`);
>                   return;
>                 }
>                 if (params["+non_branch_link"]) {
>                   // const nonBranchUrl = params["+non_branch_link"];
>                   // Route non-Branch URL if appropriate.
>                   return;
>                 }
> 
>                 if (!params["+clicked_branch_link"]) {
>                   // Indicates initialization success and some other conditions.
>                   // No link was opened.
>                   return;
>                 }
> 
>                 // A Branch link was opened
>                 const url = params.$canonical_url;
>                 const eventId = url.replace("events/", "");
> 
>                 // routing depending on deep link
>                 listener(\`/events/${eventId}\`);
>               });
>               return () => {
>                 // Clean up the event listeners
>                 Linking.removeEventListener("url", onReceiveURL);
>               };
>             },
>             async getInitialURL() {
>               // First, you may want to do the default deep link handling
>               // Check if app was opened from a deep link
>               const url = await Linking.getInitialURL();
>               // routing depending on deep link
> 
>               if (url != null) {
>                 return url;
>               }
>               // Next, you would need to get the initial URL from your third-party integration
>               // It depends on the third-party SDK you use
>               // For example, to get to get the initial URL for branch.io:
>               const params = await branch.getFirstReferringParams();
> 
>               return params?.$canonical_url;
>             }
>           }}
>         >
>           <MainNavigator />
>         </NavigationContainer>
> ```
> 
> This way, all links are opened by the native deep linking system and routed through it. Independently of routing, onsubscribe callback from rn branch is executed so that branch api is aware of your click.

do you if there is a way to implement this on the android side? because I'm having the same issue but on android

**Comment by rodgomesc** [comment]
replace, `RNBranch application:app` for  `RNBranch application:application`,  in my case the app is crashing in the production build.

why the branch.io team doesn't update this documentation, why is this issue abandoned?

**Comment by giautm** [comment]
Thank you for help me to resolve issue with RCTLinkingManager. I written a [plugin to use react-native-branch with expo](https://github.com/expo/expo/issues/12906#issuecomment-990180911)

**Comment by NicoS0** [comment]
@Vasault 

**iOS:**
- replace `app` with `application`
- if you no need routing for FB etc. you can simply return nil 

like that:
```
// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  if ([RNBranch application:application openURL:url options:options])  {
       // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    return nil;
   }
  
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

**Android:**
Make sure that in `MainActivity.java` `onNewIntent` method looks like:
```
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        RNBranchModule.onNewIntent(intent);
    }

**Comment by miladdev85** [comment]
@cbarceloc Thank you for this! But shouldn't we add `return` before 
```
[[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options];
```

**Comment by iledzka** [comment]
> if ([RNBranch application:app openURL:url options:options])

For anyone that was confused by this line:
`if ([RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    }`
There used to be [an error in the Branch documentation](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/606) .

So it should be 
`if (![RNBranch application:app openURL:url options:options])  {
        // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
    }`
or simply follow @SeanDunford 's [solution.](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/591#issuecomment-1189502870)
