### ISSUE TITLE
Sharing of Link from Android to IOS not working.

### ISSUE THREAD

**Issue by Muhamman78** [BranchMetrics/react-native-branch-deep-linking-attribution#666]
The working of links from IOS to android , IOS to IOS and Android to Android is okay, but when you share link from an android device and try to open it on an IOS device it always takes me to the app store. Anyone else facing the same issue? If yes please help me with this issue.
Thanks in advance

**Comment by jf-branch** [comment]
Hi @lyseiha, could you provide links created from both Android and iOS and match them with the experience you are facing?

**Comment by vswakao** [comment]
Anyone has solution? even i am also facing the same issue with branch, Android shared link, not opening app from iOS.

**Comment by jf-branch** [comment]
Hey @vswakao, given the context of this, you're best luck would be to create a support ticket through our site: https://help.branch.io/using-branch/page/submit-a-ticket
