### ISSUE TITLE
non_branch_link / URI should be forwarded to the app when connection to branch server is poor

### ISSUE THREAD

**Issue by sbycrosz** [BranchMetrics/react-native-branch-deep-linking-attribution#671]
## Version

React-native@0.62.2 / react-native-branch@5.0.3

## Code

```
    this._unsubscribe = branch.subscribe((params) => {
      console.log('params', JSON.stringify(params, null, 2)); // eslint-disable-line
    });
```

## Steps to reproduce

1. Set up a react-native app with branch deep linking
2. Turn off wifi  
    - Alternatively: wait for branch.io regular maintenance or 
    - Block branch.io from loading via DNS/Proxies
3. Open a registered deep-link
4. The app will print an error instead of passing through the link to the app via `uri`  or `+non_branch_link` parameters
  Error: `Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.` 

## Expected result

Opened deep-links should be passed to the app regardless of branch server status

Thanks.
Sam

**Comment by iamandiradu** [comment]
I agree. I'm getting a lot of 
`"Trouble reaching server. Please try again in a few minutes" Trouble initializing Branch.  Request to Branch server timed out. Please check your internet connectivity`
 lately, even though my connection is stable.

**Comment by raquelmsmith** [comment]
I am also getting this a lot. Tried the suggestion here to no avail: https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/844

**Comment by husseinAbdulnabi** [comment]
getting this error also.

**Comment by rbgoncalves** [comment]
Hi,

By just sending a callback to the Branch's subscribe, you are implicitly waiting for the linking AND then the branch resolve (where it tries to get params from the server ).
By looking at branch's typescript definition I've noticed that there is another way of listening to the linking, without relying on the branch server, _i.e._ perfect for handling non-branch-links.

```js
 const unsubscribe = branch.subscribe({
      // Non branch.io linking (deeplinking + web linking)
      onOpenStart: ({ cachedInitialEvent, uri }) => {
        if (!uri) return;

        // Avoid linking on hot reload
        if (cachedInitialEvent) return;

        // Avoid branch.io links (the pattern is a string with the app.link OR the custom subdomain)
        if (uri.includes(BRANCHIO_LINK_PATTERN_MATCH)) return;

        navigate(uri);
      },
      // Branch.io linking only 
      onOpenComplete: ({ params }) => {
       // Quit from execution when +non_branch_link (navigation is handled by onOpenStart
        if (params?.['+non_branch_link']) return null;

        // Do whatever you want with branch's metadata params and uri
      },
```

In a nutshell, `onOpenStart` contains the raw uri and doesn't rely on networking. `onOpenComplete` is called after making the call to the branch's server, useful for branch links only.

**Comment by saqibusmangithub** [comment]
@sbycrosz Good Day! to notify i am also getting this error even when network is completely fine on device, What can be reason ?

**Branch io version:** 3.1.0
**Device:** Samsung Galaxy S21
**Android:** Version  11

**Comment by saqibusmangithub** [comment]
@sbycrosz to add more information, we already have  Branch.io integrated in our app which is running fine on all other devices we have.

This issue is only happening on device and os that i mentioned in previous comment above.

Issue we get in branch io callback : `Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.`

**Comment by Mihai-github** [comment]
Hello, @rbgoncalves. I've noticed your approach, which seems similar to achieving the desired behavior using Linking.addEventListener. However, I'm encountering a challenge. Following your guidance, I'm now observing a URI like `app_name://open?link_click_id=some_number` within the `onOpenStart` log. I'm a bit unsure about the subsequent steps to take because the necessary information I require doesn't appear to be present in this URI.

**Comment by Mihai-github** [comment]
Currently, I've observed the issue solely on my Android phone running `version 13`. This particular version includes numerous recent modifications, which could potentially be causing the problem. It's possible that the library isn't up to date and may not be fully compatible with this version. As part of my troubleshooting efforts, I plan to obtain an Android phone with a lower version to further investigate and confirm the source of the issue.
