### ISSUE TITLE
NativeLink Support on Expo Managed Apps to get around Private Relay

### ISSUE THREAD

**Issue by Aryk** [BranchMetrics/react-native-branch-deep-linking-attribution#677]
[Current Discussion](https://forums.expo.dev/t/branch-nativelink-is-it-supported/57157/4)
[Ticket on Expo](https://github.com/expo/expo/issues/14631)

I've read through the only other [ticket regarding Nativelink support](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/668).

I'm on Expo Managed SDK 42, soon to be upgrading to SDK 43. 

**Even** SDK 43 does not have version 5.0.4 installed which means that it will not support NativeLink from branch. I have no experience with native code or writing config plugins (for EAS builds). 

Are there any plans from the react native branch team to get it working on Expo Managed?

I'm even happy to pay a developer to resolve this for me (config plugin, patch package, etc) as I estimate I will lose attribution tracking by 25% over the coming months (50% iphone users X 50% iCloud Plus users). For iCloud Plus users Private Relay is enabled by default.

**Comment by giautm** [comment]
Hey, I just write a plugin for our apps. I'm looking into this repo to find any open issue/PRs and I found this.

Can you try my plugin? If anything go wrong, please comment so I can fixed it.

https://github.com/expo/expo/issues/12906#issuecomment-990180911

**Comment by gdeluna-branch** [comment]
I believe this is resolved
