### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by jm90m** [BranchMetrics/react-native-branch-deep-linking-attribution#682]
Hello I am receiving this error after running a pod install, I have installed the latest version of branch for react native as described in here - https://help.branch.io/developers-hub/docs/react-native

![Screen Shot 2021-11-19 at 5 03 33 PM](https://user-images.githubusercontent.com/5067716/142697415-a672d7f7-3f0e-4aed-8713-0acef4438bd3.png)

**Comment by echo-branch** [comment]
Try using `pod update` instead of `pod install`. 

You may need to clear the cache as well. Delete the `Podfile.lock` and the `Pods` folder. Then run `pod update`.

**Comment by jcerone-boom** [comment]
I'm running into the same issue. When attempting to run `pod update` I get the following error: 

```
[!] Error installing Base64
[!] /usr/bin/git clone https://github.com/ekscrypto/Base64.git /var/folders/g7/r8kybh7j24j8lfkq_lwt5hnr0000gn/T/d20220512-31328-1bwwioe --template= --single-branch --depth 1 --branch 1.1.2

Cloning into '/var/folders/g7/r8kybh7j24j8lfkq_lwt5hnr0000gn/T/d20220512-31328-1bwwioe'...
fatal: 'git@github.com/ekscrypto/Base64.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by gdeluna-branch** [comment]
Closing inactive issues. Please make a new issue if it persists on the latest release.
