### ISSUE TITLE
Attempted to remove more RNBranchEventEmitter listeners than added

### ISSUE THREAD

**Issue by ilyagru** [BranchMetrics/react-native-branch-deep-linking-attribution#684]
Hello!

I started to get this error with this package. It seems it's because of deprecated `removeListener`s. Interestingly enough, the error happens only when I force reload the app with e.g. Cmd+R. If I replace them with `remove()`, the error is gone.

I'm happy to prepare a PR if you need help.

<img src="https://user-images.githubusercontent.com/18074511/147249210-3d8d2aec-0d48-4818-ba09-2caec9c73018.png" width="300" />

"react-native-branch": "5.2.1",
"react-native": "0.66.3",
iOS 15.1
Android 11

**Comment by gdeluna-branch** [comment]
Resolved.
