### ISSUE TITLE
React native upgrade: EventEmitter removeListener is deprecated in favor of EventSubscription.remove()

### ISSUE THREAD

**Issue by jayshah-swiggy** [BranchMetrics/react-native-branch-deep-linking-attribution#686]
Seeing following error on upgrading react-native to 0.66:
```
 WARN  EventEmitter.removeListener('RNBranch.initSessionError', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`. 
```

In RN > 0.65, EventEmitter.removeListener() is on path to deprecation, and can be observed from internal APIs like 
https://reactnative.dev/docs/appstate#removeeventlistener

Expecting Branch library to be updated to be in sync with the latest versions of react native.

**Comment by AbrahamMayowa** [comment]
Facing this issue too.

**Comment by gdeluna-branch** [comment]
Completed.
