### ISSUE TITLE
App is fronze when Kakao app is selected without login

### ISSUE THREAD

**Issue by livefuture009** [BranchMetrics/react-native-branch-deep-linking-attribution#687]
Hello, I am getting frozen error.

### Steps to reproduce
1. Please Install KakaoTalk app and don't login yet.
2. Called below function.
const {channel, completed, error} = await branchUniversalObject.showShareSheet(shareOptions, linkProperties, controlParams);
3. Then I am getting this screenshot.
![73E2E36F-D5D9-4851-808F-C2A8EF1BE4A5](https://user-images.githubusercontent.com/36209712/148727476-374d04b5-bc5d-4fe9-87e4-9a29e5362eff.png)
![384A7CFD-451B-4D79-9AFC-657F50B2FB5F](https://user-images.githubusercontent.com/36209712/148727485-9363d827-43a0-4cf4-a0f1-163be3e899af.png)

4. After that, app is frozen. It's working as well after I have login at kakao app.

### Environment
- **React Native version**: 0.66.4
- **React Native platform + platform version**: iOS 15.1
"react-native-branch": "^5.2.1",

Could you fix it ASAP? 

Best Regards.

**Comment by gdeluna-branch** [comment]
Closing out old issues. This is an app issue, not sdk. Please open a ticket with support https://help.branch.io/using-branch/page/submit-a-ticket
