### ISSUE TITLE
IOS unable to get deeplink params when using [[Branch getInstance] delayInitToCheckForSearchAds]

### ISSUE THREAD

**Issue by hubastard** [BranchMetrics/react-native-branch-deep-linking-attribution#689]
We followed the instructions in the Branch documentation to setup our Android and iOS project to support deeplinks and we are able to receive our deeplinks data in the params properly on both platform. But as soon as we try to support Apple Search Ads by adding `[[Branch getInstance] delayInitToCheckForSearchAds]` in our `AppDelegate.m` our deeplinks data stops being recognized by Branch and we only receive a `non_branch_link` with our url in it.

Is branch not supporting both feature at once ??

Also what is `[[Branch getInstance] delayInitToCheckForSearchAds]` doing, is it really needed if we only want to see Apple Search Ads stats in branch dashboard?

**Comment by jf-branch** [comment]
Hi @hubastard I'll bring this to the attention of the team. 

But in the meantime, the delay is meant to wait for a response from the ASA API, however, this is only meant for the [Old ASA Framework](https://help.branch.io/using-branch/docs/apple-search-ads#sdk-setup-old-framework) and is not needed if you and your team are using the [New ASA Framework](https://help.branch.io/using-branch/docs/apple-search-ads#sdk-set-up-new-framework). 

For more information: https://help.branch.io/using-branch/docs/apple-search-ads

**Comment by hubastard** [comment]
@jf-branch Alright so since we are using the latest version (1.40.2) we can safely remove `[[Branch getInstance] delayInitToCheckForSearchAds]` and ASA should still work?

Thanks.

**Comment by jf-branch** [comment]
@hubastard The majority of our clients are using the new framework. I would strongly recommend confirming with your marketing team that the expectation is to be utilizing the new framework and that the integration requirements for the [New ASA Framework](https://help.branch.io/using-branch/docs/apple-search-ads#sdk-set-up-new-framework) are all complete.
