### ISSUE TITLE
SAN Deferred deep linking api call not working

### ISSUE THREAD

**Issue by gpavlov21** [BranchMetrics/react-native-branch-deep-linking-attribution#704]
I have a problem getting the data from the deferred deep link, I'm not sure how to correctly send the params. In the documentation it says to get the data from `api2.branch.io/v1/install` but it doesn't say what params you need to send and how exactly. I tried with
 `https://api2.branch.io/v1/install?app_id=OUR_APP_ID&branch_key=OUR_KEY&branch_secret=OUR_SECRET` 
 and some other variations but I either get this error `{"code":405,"message":"HTTP 405 Method Not Allowed"}` or `"Invalid or missing app id, Branch key, or secret"`. I wrote an email to the branch support and the SAN Deferred deep linking feature is enabled for my branch account, but for that problem they haven't responded for a whole week and now I'm asking here.

**Comment by gpavlov21** [comment]
Hey @jf-branch , thank you for the quick response. San Deferred Deep Linking Case #00236282 - this is the email subject, guessing #00236282 is the Ticket #.

**Comment by jf-branch** [comment]
Thanks @gpavlov21, I've notified the team.
