### ISSUE TITLE
React Native Docs give an example that causes branch listener behavior to not work as expected. 

### ISSUE THREAD

**Issue by mljlynch** [BranchMetrics/react-native-branch-deep-linking-attribution#707]
In the [branch-react-native docs](https://help.branch.io/developers-hub/docs/react-native#android) - there is the suggestion to use the following code snippet:

```java
  @Override
  public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
        if (intent != null &&
              intent.hasExtra("branch_force_new_session") && 
              intent.getBooleanExtra("branch_force_new_session",false)) {
            RNBranchModule.onNewIntent(intent);
        }
  }
```

However, with this code, links will only trigger the branch listener when the app is opened. In order for me to trigger a new branch event even when the app is currently opened in the background. I have to change the code to this:

```java
  @Override
  public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    RNBranchModule.onNewIntent(intent);
  }
```

A few questions: 

1. Is this safe to do? 
2. If so, why is the intent check recommended by the docs?

**Comment by ap1969** [comment]
I've got the same issue:

react-native-branch v5.0.0
react-native v0.67.3

Resolved it as you have pointed out above.

**Comment by ap1969** [comment]
However, I'm now seeing the subscribed function fire multiple times when a branch link is clicked, the app moved to the background, and the link clicked again. Each repeat of this adds more and more firings. I've tried debouncing and throttling, and that's made no difference, as though some listeners are hanging around.

**Comment by ap1969** [comment]
A working project example would be great, by the way.

**Comment by mljlynch** [comment]
How are you seeing the function fire?

**Comment by ap1969** [comment]
In app.js:

```
let App = props => {
    const branchUnsubscribe = branch.subscribe(({error, params, uri}) => {
        if (error) {
          log.error('Error from Branch: ' + error);
          return;
        }

        log.debug('Params from branch', params);
        ...
    });
}
```

**Comment by ap1969** [comment]
.... AAAND I've just realised that because I've got the branch.subscribe inside the App component, that's what's causing the problem. 

I've moved it back outside, and it's only firing the once.

**Comment by scottwio** [comment]
Just to add to this seeing the same thing  `intent.hasExtra("+clicked_branch_link")` results in `false` `intent.getExtras()` is `null`

**Comment by fatlinesofcode** [comment]
same issue here

react-native-branch v5.4.0
react-native v0.68.2

**Comment by jf-branch** [comment]
The [docs](https://help.branch.io/developers-hub/docs/react-native#android-1) were updated a couple weeks ago. We apologize for the misleading integration steps, as we have a publicly open "Suggest Edits" feature that was improperly approved.
