### ISSUE TITLE
~creation_source type should be number

### ISSUE THREAD

**Issue by vincent-paing** [BranchMetrics/react-native-branch-deep-linking-attribution#709]
I noticed the typing for `~creation_source` is wrong. It should be number instead of string. This can be verified easily by creating [a deeplink from API.](https://help.branch.io/developers-hub/docs/deep-linking-api#creating-a-deep-linking-url). Putting this into `branch.subscribe` and console logging `event.params` will tell you that `~creation_source` is a number. You can also do a check like this and confirm that check returns false.

```
event.params[~creation_source] === '0' // false
```

Also by the document, these are numbers.

> Where the link was created (0 API , 1 Quick Link, 2 SDK, 3 iOS SDK , 4 Android SDK , 5 Web SDK, 6 Dynamic, 7 Third party)

Let me know if you want me to submit a PR to fix this.

**Comment by gdeluna-branch** [comment]
That'd be super helpful @vincent-paing . Our team will test/review it this week once published.

Thanks!
