### ISSUE TITLE
React native issue with branch.getLatestReferringParams on Android

### ISSUE THREAD

**Issue by otaviomorcegao** [BranchMetrics/react-native-branch-deep-linking-attribution#713]
I'm trying to offer discounts using a deep link. It's working fine on iOS, but on Android, I got the following issue.

When I click on the deep link, I am taken to the paywall screen with the applied discount. But if I close this paywall without making a payment, and go to any paid content, the paywall opens again and the discount is still applied. I realize that in Android the session is not being cleared/restarted and `branch.getLatestReferringParams()` keeps returning params. Is there something there I'm missing?

**Comment by gdeluna-branch** [comment]
Closing out inactive issues. If this is still a problem, please open a support ticket: https://help.branch.io/using-branch/page/submit-a-ticket
