### ISSUE TITLE
How to attribute custom events passed from Server to Server to specific channel/campaigns?

### ISSUE THREAD

**Issue by Cshayan** [BranchMetrics/react-native-branch-deep-linking-attribution#718]
Hi,

Is there any way to attrbute the custom events we trigger from server to server to some channels/campaigns? Currently when I trigger any event it is not attributed and all such events are coming under oragnic traffic.

Thanks.

**Comment by jf-branch** [comment]
Hi @Cshayan, if your events include the relevant device ids, https://help.branch.io/developers-hub/docs/tracking-commerce-content-lifecycle-and-custom-events#http-api---commerce, then Branch will utilize [Predictive Modeling](https://help.branch.io/using-branch/docs/branch-methodology-overview#predictive-modeling-engine-across-the-branch-platform) to attribution the s2s event back to the link click.
