### ISSUE TITLE
Sometimes deeplink open fallback url or default url

### ISSUE THREAD

**Issue by ydhnwb** [BranchMetrics/react-native-branch-deep-linking-attribution#729]
I have a react native app with branchIO on it. I am using a link to create a forgot password like this

Confirm email button from email will have a link like this: https:///my-app.app.link/forgot-password?p1=xxx&p2=yyy&etc...
Sometimes when I clicked a button with that link, it opens the app correctly.
But sometimes it doesnt work (it will open either fallback url or default url).
I need to repeat clicking button until it works.

When deeplink not works, the error also not show up because it doesnt open my app.

What problem cause this? Since it is really hard to debug

**Comment by jf-branch** [comment]
Hey @ydhnwb, Given this is related to our link services, I would strongly recommend submitting ticket to our support team https://help.branch.io/using-branch/page/submit-a-ticket
