### ISSUE TITLE
Library not found for 5.5.0

### ISSUE THREAD

**Issue by HilSny** [BranchMetrics/react-native-branch-deep-linking-attribution#731]
Hi All!

I am getting an issue with the latest version of this repo. See the below image. I checked to see that we're bringing in 1.43.1 to our Podfile.lock and we are. Any ideas?

![Screen Shot 2022-08-04 at 10 46 48 AM](https://user-images.githubusercontent.com/16581033/182890828-2746be37-14bb-464c-adf7-8c33fbf61197.png)

**Comment by HilSny** [comment]
This issue goes away when I install 5.4.1

**Comment by nsingh-branch** [comment]
Hi @HilSny, I'm trying to reproduce your issue and had a couple of questions. Which version of the Branch SDK did you update from? 

You may have already tried these, but I also had a couple troubleshooting steps that could help.

1. Running `pod install` in your project's `ios` folder 
2. Removing and reinstalling the Branch SDK
3. Deleting and reinstalling your project's `node_modules` folder

Please let me know if this helped or if the issue persists and we will look into this further. Thanks!

**Comment by HilSny** [comment]
Hi! 

We were upgrading from 5.4.1. 
1). I did run pod install and even tried clearing our build cache. 
2). The Branch sdk is brought in through cocoapods via autolinking so I'm not sure what you mean by removing and reinstalling it.
3). I cleared node_modules a couple times to test.

Were you not able to replicate it?

**Comment by nsingh-branch** [comment]
@HilSny At first I installed the React Native Branch SDK v5.5.0 directly and did not face the issue, but when I started with 5.4.1 and updated to 5.5.0, I was able to reproduce your issue. For some reason when the React Native SDK is updated, the iOS SDK isn't being updated from 1.42.0 to 1.43.1. 

**I was able to solve the issue by running `pod update` in the `ios` folder of my project.** Please try this and let me know if it resolves your issue. I'll look into this further today to try and fix it.

**Comment by HilSny** [comment]
@nsingh-branch interesting. In my podfile.lock I double checked that the Branch pod was at 1.43.1 and was still getting this issue. For now we've just decided not to upgrade but let us know when you're able to find a fix.

**Comment by gdeluna-branch** [comment]
Another option is to run

`pod deintegrate`
and then
`pod install`
