### ISSUE TITLE
branch.subscribe blank uri on android

### ISSUE THREAD

**Issue by SMaxOwok** [BranchMetrics/react-native-branch-deep-linking-attribution#735]
After an upgrade to our React Native version, we're seeing a difference in behavior with navigating to deep links while inside the app.  Right now these are only custom scheme uris, so we are simply forwarding incoming from `branch.subscribe` to the listener, which had been working fine.  We're using this in conjunction with React Navigation.

We're now seeing that on Android, the uri is blank, so it no longer opens the correct screen in-app.  It is still working on iOS.

react-native v0.69.4
react-native-branch v5.4.0
react-navigation/native v6.0.6

```
const linking = {
  subscribe(listener) {
    branch.subscribe(({ error, params, uri }) => {
      if (error) {
        console.error('Error from Branch: ' + error);

        return;
      }

      console.log('URI', uri);
      console.log('params', params);

      listener(uri);
    });
  },
  ...
};
```

iOS
```
 LOG  URI my-app://notifications
 LOG  params {"+clicked_branch_link": false, "+is_first_session": false, "+non_branch_link": "my-app://notifications"}
```

Android
```
 LOG  URI null
 LOG  params {"+clicked_branch_link": false, "+is_first_session": false, "+non_branch_link": "my-app://notifications"}
```

**Comment by hicham-amrani** [comment]
Hi @SMaxOwok, did you find a solution to your Android issue?

**Comment by SMaxOwok** [comment]
@hicham-amrani for now I have just added a block to handle those in the same way.

```
      if (params['+non_branch_link']) {
        listener(params['+non_branch_link']);

        return;
      }
```
