### ISSUE TITLE
iOS app is not being redirected/opened with url.

### ISSUE THREAD

**Issue by sadia-onyxtec** [BranchMetrics/react-native-branch-deep-linking-attribution#736]
I am working on universal links for my react native iOS app. I want the user to be redirected to a custom url if the app is not installed. I have done the following but my app is not being opened with the url.

  I have configured the branch dashboard. (Bundle Identifier & Apple App Prefix are both set correctly.)
  I have enabled the associated domains.
  I have added the url and keys in the info.plist file.
  I have added the enlistments file.
  I have added the url type and scheme in info > xcode.
  My AppDelegate file has 

```
#import <RNBranch/RNBranch.h>

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  BOOL branchOpened = [RNBranch application:application openURL:url options:options];
  if (branchOpened){
    return YES;
  }
  // Required for opening links from JS
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RNBranch continueUserActivity:userActivity] || [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}
```

Any kind of help is greatly appreciated. Thank you.

**Comment by gdeluna-branch** [comment]
Hi @sadia-onyxtec, for integration help please submit a ticket here https://help.branch.io/using-branch/page/submit-a-ticket
