### ISSUE TITLE
Error 409 : Link alias conflict 

### ISSUE THREAD

**Issue by yanzdog** [BranchMetrics/react-native-branch-deep-linking-attribution#739]
### Describe the bug

Hello! I am using branch.io for users on my app to be able to share their profiles.
Every time users tap on a button, the code below executes to create the link.

```
const path = 'users/id'
let buo = await branch.createBranchUniversalObject(path, {
  title: `title1`,
})

let linkProperties = {
  alias: path
}

let controlParams = {
  $desktop_url: 'https://example.com',
}

let { url } = await buo.generateShortUrl(linkProperties, controlParams)
```

I then changed to the `title` property from `title1` to `title2` with everything else the same, it suddenly started throwing the error. Branch does not merge the content based on `canonicalIdentifier` ... ? I would still like to use the same alias with the content (title) changed.

I don't know if this is a bug or not, but any suggestions for I want to achieve would be appreciated.

Thank in advance!

### Steps to reproduce
see above the please 

### Expected behavior
see above the please 

### SDK Version

5.5.0

### Make and Model

iPhone 13

### OS

iOS 15.6.1

**Comment by jf-branch** [comment]
Hey @yanzdog I would suggest to open a support ticket for this: https://help.branch.io/using-branch/page/submit-a-ticket

**Comment by yanzdog** [comment]
Hello @jf-branch ! I did that and no replies 😢

**Comment by jf-branch** [comment]
Do you have the ticket number?

**Comment by yanzdog** [comment]
Yes! `00283328`

**Comment by jf-branch** [comment]
Thanks @yanzdog I have escalated and you  should get a response shortly.
