### ISSUE TITLE
[android] error: local variable promise is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by gabriel1lima** [BranchMetrics/react-native-branch-deep-linking-attribution#746]
#### Package version: 5.6.1

When running `npx react-native run-android` the build failed and show 2 error messages:

1. RNBranchModule.java:455: `error: local variable promise is accessed from within inner class; needs to be declared final`

         promise.reject("RNBranch::Error::setIdentityAsync failed", error.getMessage());

3. RNBranchModule.java:457: `error: local variable promise is accessed from within inner class; needs to be declared final`

          promise.resolve(convertJsonToMap(referringParams));`

### Steps to reproduce

1. npx react-native run-android

### Expected behavior

Build successful

### SDK Version

5.2.5

### Make and Model

Xiaomi Redimi Note 8

### OS

Android 11

**Comment by gdeluna-branch** [comment]
Thanks for raising this, we'll take a look. @nsingh-branch

**Comment by EhabMostafa** [comment]
Same problem

**Comment by EhabMostafa** [comment]
Solved by adding final Promise promise to setIdentityAsync function -> node_modules\react-native-branch\android\src\main\java\io\branch\rnbranch\RNBranchModule.java

to be like this:

@ReactMethod
    public void setIdentityAsync(String identity, final Promise promise) {
     ...
    }

**Comment by nsingh-branch** [comment]
Fixed in the latest release v5.6.2
