### ISSUE TITLE
branch.openURL error: object is null or undefined react native

### ISSUE THREAD

**Issue by GHEduardoAugusto** [BranchMetrics/react-native-branch-deep-linking-attribution#750]
### Describe the bug

Hi Guys, 

I doing branch.io integration into an app with react-native and
following the documentation: https://help.branch.io/developers-hub/docs/react-native

My project is in version: 

- react-native: 0.68.2 
- react-native-branch 5.6.2

I am trying open the url, but I'm getting error:
"Object is null or undefined react native"

I followed the exemple:
https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/tree/master/examples

```
import branch from 'react-native-branch'

branch.openURL = async () => {
    const url = 'https://zjef.test-app.link/n4efBZnSu8';
    try {
      await branch.openURL(url);
      this.addResult('success', 'openURL', url);
    }
    catch (err) {
      this.addResult('error', 'openURL', err.toString());
    }
}
```

### Expected behavior
Open URL and getting data in branch.io dashboard

**Comment by JagadeeshKaricherla-branch** [comment]
you are overriding the branch method definition for openURL which is wrong
`branch.openURL = async () => {`

if you want to call branch's openURL method you can do :

```
async function openBranchLink() {
const url = 'https://zjef.test-app.link/n4efBZnSu8';
    try {
      await branch.openURL(url);
      this.addResult('success', 'openURL', url);
    }
    catch (err) {
      this.addResult('error', 'openURL', err.toString());
    }
}
```

or

```
  openBranchLink = async () => {
    const url = 'https://zjef.test-app.link/n4efBZnSu8';
    try {
      await branch.openURL(url);
      this.addResult('success', 'openURL', url);
    }
    catch (err) {
      this.addResult('error', 'openURL', err.toString());
    }
  }
```

**Comment by jf-branch** [comment]
@GHEduardoAugusto wanted to follow up and see if you are still being faced with this issue or if you were able to resolve it with @JagadeeshKaricherla-branch's comment?
