### ISSUE TITLE
No visible @interface for 'Branch' declares the selector 'checkPasteboardOnInstall'

### ISSUE THREAD

**Issue by xiaohui-gsv** [BranchMetrics/react-native-branch-deep-linking-attribution#759]
### Describe the bug

I want to enable the NativeLink, and there is an error when I paste the code to XCode.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/38554198/202331789-459661b2-4786-4b38-8d11-cc9f93344849.png">

BTW, this code is optional, right? If I don't put it into my IOS project, the Deferred Deep Linking still can work right? Thank you.

### Steps to reproduce

Copy the code from React Native document.

### Expected behavior

shouldn't show an error.

### SDK Version

5.6.2

### Make and Model

XCode 14.1

### OS

macOS ventura 13.0

**Comment by jf-branch** [comment]
Hey @xiaohui-gsv We have not exposed that method to the RNBranch Module directly but you can access it through the branch instance itself via: 
 [[RNBranch branch] checkPasteboardOnInstall];

**Comment by jf-branch** [comment]
Hey @xiaohui-gsv, could you confirm what version of Branch you have in your podfile.lock ? 

If you are on an older version, you may want to delete your podfile.lock to clear the cache and rerun pod install.

**Comment by xiaohui-gsv** [comment]
Hi @jf-branch , you are correct, the version in podfile.lock is old, thank you so much.
BTW, this code is optional, right? If I don't put it into my IOS project, the Deferred Deep Linking still can work right?

**Comment by jf-branch** [comment]
Happy to hear this is resolved. 

We will fallback to utilizing probabilistic matching, so you wont have a 100% success rate as does [NativeLink deterministic deferred deep linking](https://help.branch.io/using-branch/docs/nativelink-deferred-deep-linking), but yes that is correct.
