### ISSUE TITLE
Cannot get Apple Search Ads attribution

### ISSUE THREAD

**Issue by gabimoncha** [BranchMetrics/react-native-branch-deep-linking-attribution#760]
### Describe the bug

Hi, I've been trying to understand from the documentation how exactly can I get the Apple Search Ads attribution.
I've updated my AppDelegate.m file with the following:
```
  [RNBranch.branch delayInitToCheckForSearchAds];
  [RNBranch.branch useLongerWaitForAppleSearchAds];
  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES];
```

And I'm loggin all the options that are coming from `branch.subscribe`

I've also added Ads.Framework to the Linked Libraries in Xcode. Am I missing something?

### Steps to reproduce

1. Follow React Native documentation

### Expected behavior

I was expecting to see the Apple Search Ads attribution parameters when logging branch.subscribe.

### SDK Version

5.5.0

### Make and Model

iPhone XR

### OS

iOS 16.1.1

**Comment by echo-branch** [comment]
That API is for the older Apple Search Ads attribution. If you're testing on a newer device, it will not return anything unless you've accepted the AppTrackingTransparency dialog prior to initializing Branch. On older devices, it will work as expected.

Now for newer devices, we use the Apple Search Ads attribution api in `AdServices.framework`. This new API handles attribution on the server side, so you'll get no feedback on the device. The attribution data will be available on the Branch Dashboard.

**Comment by gabimoncha** [comment]
Thank you very much for the reply. I’ve indeed added `AdServices.framework` as according to the [documentation](https://help.branch.io/using-branch/docs/apple-search-ads#sdk-set-up-new-framework), but there was a typo in my initial post.
Even so, after integrating it, we still don’t get any iOS parameters in the options returned in the `branch.subscribe` method.

**Comment by jf-branch** [comment]
@gabimoncha Could you file a support ticket through https://help.branch.io/using-branch/page/submit-a-ticket? 

We would need logs to better understand what the SDK is collecting from ASA and sending to our backend and cross reference it with the attribution results to see what should be returned. 

To help expedite our support team, if you could test with Branch.enableLogging() before the init session within the AppDelegate and provide the Branch logs that would be super beneficial. Additionally please share us your support case number here.

**Comment by gabimoncha** [comment]
@jf-branch @echo-branch thank you for your help. I’ve opened a support ticket and the case number is 00296551
