### ISSUE TITLE
Receiving attributes in install param but not in branch.getFirstReferringParams()

### ISSUE THREAD

**Issue by rizshivalli** [BranchMetrics/react-native-branch-deep-linking-attribution#765]
### Describe the bug

I have implemented the react-native-branch library with version ^5.6.2 and the Branch SDK is triggering the 'Install/reinstall' event with the correct attributes when the app is installed through an advertisement link. However, these same attributes are not being retrieved when using the branch.getFirstReferringParams() method, nor are they being returned in the params object of the branch.subscribe() callback.
````
  branch
        .getFirstReferringParams()
        .then((installParams) => {
          // params from original install
          console.log(installParams);
        })
        .catch((err) => {
          console.log('Error in Branch getFirstReferringParams', err);
        });

````
nor it is coming in the 

````
branch.subscribe(({error, params, uri}) => {
console.log(params)
}

````

### Steps to reproduce

1. Implement the Branch SDK into your app.
2. Click on an advertisement link that includes attributes.

3. Attempt to retrieve the attributes using the branch.getFirstReferringParams() method or the params object in the branch.subscribe() callback.

### Expected behavior

According to the documentation, you can retrieve the attributes passed through an advertisement link when installing an app using the branch.getFirstReferringParams() method or the params object in the branch.subscribe() callback. These are the attributes that should be returned when using these methods

````
BranchParams {
  "~channel"?: string;
  "~feature"?: string;
  "~tags"?: string[];
  "~campaign"?: string;
  "~stage"?: string;
  "~creation_source"?: string;
  "~referring_link"?: string;
  "~id"?: string;
  "+match_guaranteed": boolean;
  "+referrer"?: string;
  "+phone_number"?: string;
  "+is_first_session": boolean;
  "+clicked_branch_link": boolean;
  "+click_timestamp"?: number;
  "+url"?: string;
  "+rn_cached_initial_event"?: boolean;
  [data: string]: AnyDataType;
}
````

### SDK Version

5.6.2

### Make and Model

All physical devices

### OS

iOS and Android

### Additional Information/Context

We are able to see all the attributes, including the AAID, in the default 'install' event that is triggered by the SDK. However, these attributes are not present in the response of either the branch.getFirstReferringParams() method or the params object of the branch.subscribe() callback. 

Without the correct attribution, this is all that is being outputted in the params object.

````
 {
    "CLICKED_BRANCH_LINK": false,
    "IS_FIRST_SESSION": true,
    "RN_CACHED_INITIAL_EVENT": true
  }
````

**Comment by RalissonMattias** [comment]
Same problem

**Comment by rizshivalli** [comment]
@RalissonMattias Contact Branch Support and ask them to add your app to SAN Deferred Deep linking whitelist. It resolved my problem
