### ISSUE TITLE
Lack params if app is opened from custom domain link

### ISSUE THREAD

**Issue by blueberry6401** [BranchMetrics/react-native-branch-deep-linking-attribution#793]
### Describe the bug

After setup my custom subdomain, I got 2 links
1. My custom link: sub.my_domain.com
2. App.link: myapp.app.link

Using branch.subscribe, params I received is different between 2 links. The link with custom subdomain is much less information than the 2nd one.

### Steps to reproduce

1. Open custom subdomain link: `https://sub.my_domain.com?abc=123`
branch.subscribe got params:
```
{
    "+non_branch_link": "https://sub.my_domain.com?abc=123",
    "+is_first_session": false,
    "+clicked_branch_link": false
}
```
2. Using `https://myapp.app.link?abc=123`
```
{
    "~creation_source": 6,
    "+is_first_session": false,
    "abc": "123",
    "+clicked_branch_link": true,
    "+match_guaranteed": true,
    "~id": 0,
    "+click_timestamp": 1677243551,
    "~referring_link": "https://myapp.app.link?abc=123"
}
```

### Expected behavior

Those 2 links' behavior should be the same. 

Update 1: If using quick link created from Branch dashboard, it works normally (custom subdomain link) with all params I set up.

### SDK Version

5.7.0

### Make and Model

iPhone 12 Pro

### OS

iOS 16.3.1

**Comment by raazatul7** [comment]
I have same issue with the params but only if I create it thru backend code, can't get the params

**Comment by jf-branch** [comment]
Hey @blueberry6401, for iOS builds you must declare your custom domain in the info.plist for the key branch_universal_link_domains, https://help.branch.io/developers-hub/docs/ios-advanced-features#return-yes-to-continueuseractivity this is of course also assuming your domains have been properly added to the Branch Dashboard as well.

**Comment by raazatul7** [comment]
> Hey @blueberry6401, for iOS builds you must declare your custom domain in the info.plist for the key branch_universal_link_domains, https://help.branch.io/developers-hub/docs/ios-advanced-features#return-yes-to-continueuseractivity this is of course also assuming your domains have been properly added to the Branch Dashboard as well.

Thanks for the reply
I fixed it by removing `useTestInstance` from the AppDelegate file.

**Comment by jf-branch** [comment]
yeah your case sounds like a Branch Key<> Branch Link mismatch. 

your live app.link will only return link data on your live Branch Key, and the same goes with your test Branch key and test app.links.
