### ISSUE TITLE
Branch has been deprecated in favor of BranchSDK warning shown after pod install

### ISSUE THREAD

**Issue by vkundapur** [BranchMetrics/react-native-branch-deep-linking-attribution#798]
### Describe the bug

I am getting a warning `Branch has been deprecated in favor of BranchSDK` when I do a `pod install`

### Steps to reproduce

1. Add Branch React Native SDK v5.7.0 to your react native project
2. Navigate to iOS folder in the project
3. Run the command `pod Install`

### Expected behavior

No warning should be show as it's on the latest version

### SDK Version

5.7.0

### Make and Model

iPhone 14 Pro Max

### OS

16.2

**Comment by angelo-hub** [comment]
bump

**Comment by jf-branch** [comment]
@angelo-hub could you delete your podfile.lock and re-run pod install, or you can run pod update Branch and see if you are still facing the issue?

**Comment by cgonzalez-oc** [comment]
Any updates on this issue? since it's a blocker for building somehow... I tried removing Podfile.lock and `pod install` and I still getting the same warning at the end of the instalation
