### ISSUE TITLE
Expo Web Platform Support

### ISSUE THREAD

**Issue by julianpensionjar** [BranchMetrics/react-native-branch-deep-linking-attribution#849]
### Describe the feature

More a question...but after battling for a while to get a version of this library working with Expo SDK 47 (also using https://www.npmjs.com/package/@config-plugins/react-native-branch), I discovered it does not work for the web platform (by which I mean Expo's support for web using react native codebase via react-native-web). Does this library support this use case, or has anyone had success making it do so? I can't readily see a (Non-Native) React library for branch that I could potentially switch out for the web channel.

Using:
* Expo SDK 47
* react-native-branch: 5.7.0 (I have EAS build issues with 5.9.0)
* @config-plugins/react-native-branch: 4.0.0

When attempting to run the web app in development, I get this error:

```
TypeError: Cannot read properties of undefined (reading 'STANDARD_EVENT_ADD_TO_CART')
./node_modules/react-native-branch/src/BranchEvent.js
C:/Users/JulianMclean/Github/pensionjar/jarvis-frontend/node_modules/react-native-branch/src/BranchEvent.js:208
  205 |  * Standard Add to Cart event
  206 |  * @type {string}
  207 |  */
> 208 | BranchEvent.AddToCart = RNBranch.STANDARD_EVENT_ADD_TO_CART
  209 | 
  210 | /**
  211 |  * Standard Add to Wishlist event
```

The only way I've found around this so far is to implement a platform-specific "shim" where I fake the react-native-branch for web (a technique that has worked for other libs that don't support web). i.e.:
* A file called branch.native.ts that merely "proxies" to react-native-branch via import/export
* A file called branch.ts that provides a matching fake implementation of the branch object

The latter is then automatically picked up for the web compile, getting round the error, but of course I will have no access to the branch functionality either. Given our RN app is intended to support android, ios AND web this is likely a problem - I'm new to branch.io but the goal is to implement deferred deep linking with a single set of links for affiliate attribution (we already have deep linking across all 3 channels, but need the "deferred" part to support the app install process.

**Comment by Hadjimina** [comment]
Hi @julianpensionjar 

how exactly did you get this running? I'm familiar with the "shim" approach but I can't get it to run even if I'm just running it on the web. I have tried running it with Helemt and with injecting it into the DOM but all lead to the same issue you outlined.

Can you share a bit more about how you got it working (ideally the code 😊)

Have a good one!

**Comment by julianpensionjar** [comment]
@Hadjimina It's a little bit lost in memory I'm afraid, so difficult to disambiguate the issues, however I can tell you where we settled on for now:
- Currently remain on Expo SDK 46 (although I know we're going to have to upgrade at some point due to Google Play reqs)
- Using react-native-branch version 5.7.0 and @config-plugins/react-native-branch version 3.0.0
- Use the platform "shim" method described above to effectively disable it for the web channel (I didn't find a solution to this I'm afraid...now we have deferred deep linking working for the native apps using branch.io, the web channel/app is a little less of a concern for us, as it was primarily used as a signup flow where new users didn't have the app yet)

I'll try and post here if we ever circle back on this and try to get something working for the web, but unlikely to be a priority for a while. Also appreciate any info if you are successful!

**Comment by kaitlyn-lighthouse** [comment]
I was able to get around this in a similar way, but instead of disabling branch functionality entirely on web, I used the Web SDK linked in the docs instead

**Comment by Hadjimina** [comment]
Yeah, we ended up using the web SDK on the web, For some reason though some of the params in the web SDK did not work as documented and we had to use a slightly hacky approach to make it work. Works now though!
