### ISSUE TITLE
Android - Crash app when build APK with version 5.4.0

### ISSUE THREAD

**Issue by dangnguyen1004** [BranchMetrics/react-native-branch-deep-linking-attribution#863]
### Describe the bug

Build Android apk with version 5.4.0 will cause crash app

Upgrade to 5.9.0 will resolve the problem

### Steps to reproduce

Build app

### Expected behavior

App not crash

### SDK Version

dont know

### Make and Model

Vsmart Joy 4

### OS

Android 11

**Comment by gdeluna-branch** [comment]
Please reopen when you have steps to reproduce a bug on the latest version.
