### ISSUE TITLE
Referral link function isn't woking stable 

### ISSUE THREAD

**Issue by tuanngocptn** [BranchMetrics/react-native-branch-deep-linking-attribution#864]
### Describe the bug

Hello all guys.

I just inited the referral link for my project and testing for preparing the next my company campaign. But this function working not really perfect. And this is the information.

- For the ios with 3G/4G connection: all referral link work smooth for all devices.
- For the ios with wifi connection: fail about 50% (21/40) => that can't get param referral.
- For the android: Fail all google pixel device. And fail about 10~12% (4/30)

Please help me for fixing this problem. I'm in the custom pricing plan. And I can't connect to any support channel now.

### Steps to reproduce

1. Create a referral link.
2. Send to other people, who haven't install the application.
3. Install app on the new device.
4. Check the link that include the referral params or not.

### Expected behavior

receive the referral parameter after install the application.

### SDK Version

5.8.0

### Make and Model

ip13, ip13pro, 13promax, 13mini, ip12, ip12pro, 12promax, 12mini, ip14, ip14pro, 14promax, ip8, ip7. And a lot android device

### OS

Ios 13+ and some android version

**Comment by gdeluna-branch** [comment]
If you submitted a ticket here https://help.branch.io/using-branch/page/submit-a-ticket let us know your ticket # and we'll follow up.

**Comment by tuanngocptn** [comment]
Ok thank @gdeluna-branch. I just summited the ticket. Hope you will follow the problem soon.
And I update the newest test case.

Seem Like problem only in Ios with wifi connection.

iPhone XS
1 pass
2 fail (wifi)
3 pass (4g)s
4 pass (wifi)
5 pass
6 fail
7 pass
8 fail
9 pass
10 pass

Iphone 13
1 pass
2 pass
3 pass
4 pass
5 pass
6 pass
7 fail
8 pass
9 fail
10 pass

Redmi
1 pass
2 pass
3 pass
4 pass
5 pass
6 pass
7 pass
8 pass
9 pass
10 pass

iPhone 8
1 pass
2 pass
3 fail
4 pass
5 pass
6 fail
8 fail
9 pass
10 fail

Samsung 
1. Pass
2 pass
3 pass
4 pass
5 pass
6 pass
7 pass
8 pass
9 pass
10 pass

iPhone 14
1 pass
2 pass
3 pass
4 fail
5 fail
6 fail
7 fail
8 pass
9 pass
10 pass

iPhone 11 (Trong)
1 fail
2 fail
3 pass
4 pass
5 pass
6 pass
7 pass
9 pass
10 pass

Oppo
1 pass
2 pass
3 pass
4 pass
5 pass
6 pass
7 pass
8 pass
9 pass
10 pass

Xiaomi
1 pass
2 pass
3 pass
4 pass
5 pass
6 pass
7 pass

iPhone XS Max
1 pass
2 pass
3 fail
4 pass
5 fail
6 pass
7 pass
8 pass
9 fail
10 fail

phone 11 (Van)
1 fail 
2 fail
3 pass
4 pass
5 pass
6 pass
7 pass
8 pass
9 pass
10 pass
11 fail

iPhone 11(test)
1 pass
2 fail
3 pass
4 pass
5 fail
6 pass
7 fail
8 pass
9 pass
10 pass

**Comment by tuanngocptn** [comment]
Hello @gdeluna-branch

**Comment by gdeluna-branch** [comment]
Can you share the ticket number? We'll need that to follow up. Thanks

**Comment by tuanngocptn** [comment]
Hello @gdeluna-branch.

**Comment by nsingh-branch** [comment]
> Hello @gdeluna-branch.
> 
> Don't have any ticket number on the email.
> 
> Where I can find that?
> 
> Thanks

Hi @tuanngocptn, the case number should be in the support email's title. It should look something like "Case #00346254".

**Comment by tuanngocptn** [comment]
Hello @nsingh-branch 

This is the email from support team. And don't have any case number.

<img width="708" alt="image" src="https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/assets/22292704/38019b3f-8820-407b-a4e0-834c8f7bb9b8">

Thanks.

**Comment by pawanpal-branch** [comment]
Hi @tuanngocptn Apologies for the delay happened. I replied on the support ticket - 00343221
Further communication will take place there. Thanks.

**Comment by simistern** [comment]
Hello I am dealing with the same issue. Can we please provide some kind of public help on this issue as well?
