### ISSUE TITLE
issue initializing branch on android (expo)

### ISSUE THREAD

**Issue by jacobo-jaramillo** [BranchMetrics/react-native-branch-deep-linking-attribution#865]
### Describe the bug

since yesterday branch is unable to reach it's servers and it's happening just in android

```javascript
{"params": {"error_message": "Trouble reaching server. Please try again in a few minutes"}}
```

### Steps to reproduce

1. set branch.subscribe (it's integrated with react navigation)

### Expected behavior

reach branch servers and let my app to start

### SDK Version

5.4.0

### Make and Model

Samsung Note 10 Lite

### OS

Android 12

**Comment by Mihai-github** [comment]
+1
