### ISSUE TITLE
Can't initialize branch on Android

### ISSUE THREAD

**Issue by mkw2000** [BranchMetrics/react-native-branch-deep-linking-attribution#866]
### Describe the bug

Every time I try to initialize branch on Android I get the error `Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.
`
There are no connectivity issues on the device. This issue started occurring in production using SDK version 5.4.0 and I was able to reproduce it here on version 5.9.0 as well https://github.com/mkw2000/branch-test

### Steps to reproduce

1. Install react-native-branch following [instructions in docs](https://help.branch.io/developers-hub/docs/react-native#configure-app)
2. call branch.subscribe
3. error occurs `Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.
`

### Expected behavior

Connect to branch successfully

### SDK Version

5.4.0 , 5.9.0

### Make and Model

Samsung S22 Ultra

### OS

Android 13

**Comment by Mihai-github** [comment]
Hey, I have the same issue, did you solved got any solution for this?

**Comment by Mihai-github** [comment]
@mkw2000 What I've discovered in my testing journey to find out what is the problem I came to the result after testing on different android devices the version of android 13 has this issue, did some came to other solution or has found a fix?

**Comment by DevCraftsmanShubham** [comment]
Why this issue is closed? In android 13 still not working
