### ISSUE TITLE
 onOpenComplete event of branch.subscribe firing many times on IOS

### ISSUE THREAD

**Issue by vaibhavs2** [BranchMetrics/react-native-branch-deep-linking-attribution#868]
### Describe the bug

As i am not getting any data though react-native Linking API when branch link triggers, I have used `branch.subscribe
`  and `onOpenComplete` event within `branch.subscribe` keep on firing multiple times

```javascript
    const branchListener = branch.subscribe({
      onOpenComplete: ({ error, params, uri }) => {
        console.log("this keep on firing infinite time");
        if (error) {
          Sentry.Native.captureMessage(
            "subscribe onOpenComplete, Error from opening uri: " +
              uri +
              " error: " +
              error
          );
        } else if (params) {
          if (!params["+clicked_branch_link"]) {
            if (params["+non_branch_link"]) {
              Linking.openURL(uri as string);
              // Route based on non-Branch links
            }
          } else {
            // for now branch is not opening particular screen for IOS only
            // so executing manually
            // Route based on Branch link data
            Linking.openURL(params.$deeplink_path as string);
          }
        }
      },
    });
    
```

I am on these version:
"react-native-branch": "^5.4.0",
"@config-plugins/react-native-branch": "^2.0.0",
"expo": "^46.0.0",
"react-native": "0.69.9",

Also tried upgrading to version:
"react-native-branch": "^5.9.0"
"@config-plugins/react-native-branch": "^4.0.0",

### Steps to reproduce

1. Try the code given in description 
2.
3.

### Expected behavior

it should fire once whenever branch link gets clicked, 

### SDK Version

5.4.0

### Make and Model

iphone 12

### OS

ios 16.3.1

**Comment by Yusuf-Ismail-Homage** [comment]
@vaibhavs2 would you be able to share where in your code you have defined the `branchListener` you shared above?

**Comment by vaibhavs2** [comment]
@Yusuf-Ismail-Homage I tried two ways

I have screen component hierarchy as follow
```javascript
<App>
<Context>
    <ReactNavigation>
         <HomeScreen/>
    </ReactNavigation>
<Context/>
<App/>
```
Very first time i had subscribed in HomeScreen.tsx
```javascript
// HomeScreen.tsx
useEffect(()=> {
 const branchListener = branch.subscribe()
return branchListener
}, [])
```

then I tried in App.tsx too
```javascript
//App.tsx
useEffect(()=> {
 const branchListener = branch.subscribe()
return branchListener

}, [])
```
I am sure and checked useEffect is executing only one time,

**Comment by Yusuf-Ismail-Homage** [comment]
At the very least the function is running for you (it does not work at all for me).

If you haven't yet, you can try adding the `branch.json` file to your project as described in the documentation here:
[https://help.branch.io/developers-hub/docs/react-native#defer-initialization-for-plugin-runtime](https://help.branch.io/developers-hub/docs/react-native#defer-initialization-for-plugin-runtime)

Apparently their SDK has a lot of potential for race issues.

From the snippets, it looks like you're using React Navigation. Would you be able to share what version you're using, and if you modified your `AppDelegate.m` file at all during setup of either React Navigation or Branch?

**Comment by vaibhavs2** [comment]
@Yusuf-Ismail-Homage 
I have   `"@react-navigation/native": "^5.8.9"` and i didn't changed anything from native sides as I am using expo so  ["@config-plugins/react-native-branch": "^2.0.0"](https://npm.io/package/@config-plugins/react-native-branch/v/2.0.0), these config-plugins adds the required native codes for me

**Comment by vaibhavs2** [comment]
solved

It was a implementation mistake 
i was calling react-native's Linking.openUrl() api after getting the `onOpenComplete` event from branch and that was resulting in a endless loop.

**Comment by vishaledkey** [comment]
@vaibhavs2 what did you use then? I'm using react navigation with the branch, and Linking.openURL() is the only thing working for me branch.openURL() didn't work.

**Comment by vaibhavs2** [comment]
Hello, @vishaledkey , @ducpt-bili 
You can use react-navigation to navigate to particular screen
[check it ](https://reactnavigation.org/docs/navigation-container#ref) out, this is how you can use navigation reference outside of your navigation context to navigate to screens

```javascript

export const navigationRef = React.createRef<NavigationContainerRef>();
export const isReadyRef = React.createRef<boolean | null>();

export function globalNavigate(name: string, params?: { [key: string]: any }) {
  if (isReadyRef.current && navigationRef.current) {
    // Perform navigation if the app has mounted
    navigationRef.current.navigate(name, params);
  } else {
    // You can decide what to do if the app hasn't mounted
    // You can ignore this, or add these actions to a queue you can call later
  }
}
```

within branch

```javascript
const branchSubscription = branch.subscribe({
      onOpenComplete: ({ error, params, uri }) => {
        if (error) {
       
        } else if (params) {
          const deepLink = getDeepLinkFromBranch(params, uri);
          if (deepLink) {
              const { screenName, params } =
                extractScreenParamsFromDeepLink(deepLink);
              globalNavigate(screenName, params);
          }
        }
      },
    });
```
