### ISSUE TITLE
Branch io subscribe first listener is never removed

### ISSUE THREAD

**Issue by tiagotwistag** [BranchMetrics/react-native-branch-deep-linking-attribution#870]
### Describe the bug

Yesterday, while I was fixing a problem in our app, I noticed something really strange with the branch.io subscribe listener. It seemed like it was triggering more times than it should, and sometimes it was using old data. After some digging, I figured out that if we quickly remove the first listener right after adding it, it doesn't get properly cleaned up. As a result, the first listener sticks around and stays connected to the subscribe event along with the new one we added. I also noticed that the clean up function is called for the first listener as expected, so I'm assuming there's some issue on the native side or how fast the message goes trough the bridge.

In simple terms, we end up with two listeners: the original one and the latest one. This causes big issues for us because we treat authenticated and non-authenticated users differently. Since the old listener fires first and has outdated data, it always thinks the user is not authenticated.

I've made a sample repository that shows how to reproduce this issue. You can find the link [here](https://github.com/tiagotwistag/branch-io-listener-cleanup). I've also included a demo that demonstrates the problem. 

**Note:** I've kept it simple by configuring the minimum to have branch.io running. I also only configured it for iOS, plus I used logs only for demonstration purposes.

https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/assets/88672357/81852103-50ae-49ab-8afb-882b3736bdb7

### Steps to reproduce

1. Run the app
2. Set the app into background
3. Bring it into foreground
4. watch logs, you will notice that the first listener is firing

### Expected behavior

First listener should be removed.

### SDK Version

5.8.0

### Make and Model

iPhone 14 Pro Max

### OS

16.2

**Comment by tiagotwistag** [comment]
Any update on this?

**Comment by mbcsm** [comment]
I'm running into the exact same problem, has there been any progress made in this issue?

**Comment by tiagotwistag** [comment]
This issue still affects us, could you possibly go over it and see if there's any improvement that can be made on your side?

**Comment by tiagotwistag** [comment]
This is still relevant

**Comment by tiagotwistag** [comment]
Can we re-open this? and possibly look into it?
