### ISSUE TITLE
Android 13 - Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later

### ISSUE THREAD

**Issue by Mihai-github** [BranchMetrics/react-native-branch-deep-linking-attribution#874]
### Describe the bug

 branch.subscribe function throws this error (Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later) on Android 13 devices but works on Android devices lower than version 13

### Steps to reproduce

1. setup on android branch.io 
2. inside the app.tsx add the following code:
```
useEffect(() => {
branch.subscribe(({
                onOpenStart: ({ uri, cachedInitialEvent }) => {
                    console.log({ uri, cachedInitialEvent });
                },
                onOpenComplete: async ({ error, uri, params }) => {
                    console.log({ error, uri, params });
                },
            }));
}, [])
```
3. When the app loads the log will show the error regarding poor network connectivity 

### Expected behavior

The expected behavior will be to have the ability to use the library also on Android devices witch run on version 13

### SDK Version

5.9.0

### Make and Model

Samsung S20

### OS

Android 13

### Additional Information/Context

Tested the behavior on both an emulator and also on an older physical device that runs on Android version 6 and the error never showed.

**Comment by rares-lupascu** [comment]
+1
